# HEY LOOK! THIS IS STILL FULL OF INCOMPLETENESS (AND BUGS)!!

import fakesubwayapis

class api (fakesubwayapis.fakesubwayapi) :

    def __init__ (self) :

        fakesubwayapis.fakesubwayapi.__init__(self)

        # http://www.tfl.gov.uk/tfl/livetravelnews/departureboards/default.asp

        self.lines = {
            'B' : 'Bakerloo',
            'D' : 'District',
            'H' : 'Hammersmith and City',
            'M' : 'Metropolitain',
            'N' : 'Northern',
            'O' : 'Circle',
            'P' : 'Piccadilly',
            'V' : 'Victoria',
            'W' : 'Waterloo and City',
            }
        
        self.stations = {

            #

            "ACT" : "Acton Town",
            "ALD" : "Aldgate",
            "ALE" : "Aldgate East",            
            "BST" : "Baker Street",
            "BNK" : "Bank",
            "BAR" : "Barbican",            
            "BAY" : "Bayswater",
            "BLF" : "Blackfriars",
            "CST" : "Cannon Street",            
            "EMB" : "Embankment",
            "ESQ" : "Euston Square",
            "EUS" : "Euston",
            "FAR" : "Farringdon",
            "GRD" : "Gloucester Road",            
            "GPS" : "Great Portland Street",            
            "KXX" : "King's Cross St. Pancras",
            "LST" : "Liverpool Street",            
            "MAN" : "Mansion House",
            "MON" : "Monument",
            "MGT" : "Moorgate",            
            "NHG" : "Notting Hill Gate",
            "OXC" : "Oxford Circus",            
            "SSQ" : "Sloane Square",            
            "SKN" : "South Kensington",
            "SJP" : "St. James's Park",            
            "HST" : "High Street Kensington",
            "VIC" : "Victoria",
            "WMS" : "Westminster",
            "TEM" : "Temple",
            "THL" : "Tower Hill",            
            "FPK" : "Finsbury Park",
            "ERB" : "Edgware Road",
            
            # Bakerloo
            
            "BBST" : "Baker Street",            
            "CHX" : "Charing Cross",
            "BERB" : "Edgware Road (Bakerloo)",
            "ELE" : "Elephant & Castle",
            "BEMB" : "Embankment",            
            "HSD" : "Harlesden",
            "HAW" : "Harrow & Wealdstone",
            "KGN" : "Kensal Green",
            "KNT" : "Kenton",
            "KPK" : "Kilburn Park",
            "LAM" : "Lambeth North",
            "MDV" : "Maida Vale",
            "MYB" : "Marylebone",
            "NWM" : "North Wembley",
            "BOXC" : "Oxford Circus",
            "PAD" : "Paddington",
            "PIC" : "Piccadilly Circus",
            "QPK" : "Queen's Park",
            "RPK" : "Regent's Park",
            "SKT" : "South Kenton",
            "SPK" : "Stonebridge Park",
            "WAR" : "Warwick Avenue",
            "WLO" : "Waterloo",
            "WEM" : "Wembley Central",
            "WJN" : "Willesden Junction",

            # Central
            
            "CBNK" : "Bank",
            "BDE" : "Barkingside",
            "BNG" : "Bethnal Green",
            "BDS" : "Bond Street",
            "BHL" : "Buckhurst Hill",
            "CYL" : "Chancery Lane",
            "CHG" : "Chigwell",
            "DEB" : "Debden",
            "EBY" : "Ealing Broadway",
            "EAC" : "East Acton",
            "EPP" : "Epping",
            "FLP" : "Fairlop",
            "GHL" : "Gants Hill",
            "GRH" : "Grange Hill",
            "GFD" : "Greenford",
            "HAI" : "Hainault",
            "HLN" : "Hanger Lane",
            "HOL" : "Holborn",
            "HPK" : "Holland Park",
            "LAN" : "Lancaster Gate",
            "LEY" : "Leyton",
            "LYS" : "Leytonstone",
            "CLST" : "Liverpool Street",
            "LTN" : "Loughton",
            "MAR" : "Marble Arch",
            "MLE" : "Mile End",
            "NEP" : "Newbury Park",
            "NAC" : "North Acton",
            "NHT" : "Northolt",
            "CNHG" : "Notting Hill Gate",
            "COXC" : "Oxford Circus",
            "PER" : "Perivale",
            "QWY" : "Queensway",
            "RED" : "Redbridge",
            "ROD" : "Roding Valley",
            "RUG" : "Ruislip Gardens",
            "SBC" : "Shepherds Bush (Central Line)",
            "SNB" : "Snaresbrook",
            "SRP" : "South Ruislip",
            "SWF" : "South Woodford",
            "STP" : "St. Paul's",
            "SFD" : "Stratford",
            "THB" : "Theydon Bois",
            "TCR" : "Tottenham Court Road",
            "WAN" : "Wanstead",
            "WAC" : "West Acton",
            "WRP" : "West Ruislip",
            "WCT" : "White City",
            "WFD" : "Woodford",
            
            # Circle
                 
            "OALD" : "Aldgate",
            "OALE" : "Aldgate East",
            "OBST" : "Baker Street",            
            "OBAR" : "Barbican",
            "BKG" : "Barking",
            "OBAY" : "Bayswater",
            "OBLF" : "Blackfriars",
            "BWR" : "Bow Road",
            "BBB" : "Bromley-by-Bow",
            "OCST" : "Cannon Street",
            "EHM" : "East Ham",
            "OERD" : "Edgware Road (H & C)",
            "OEMB" : "Embankment",            
            "OESQ" : "Euston Square",
            "OFAR" : "Farringdon",
            "OGRD" : "Gloucester Road",
            "OGPS" : "Great Portland Street",
            "HMS" : "Hammersmith (Circle and H&C)",
            "OHST" : "High Street Kensington",
            "OKXX" : "King's Cross St. Pancras",
            "LBG" : "Ladbroke Grove",
            "OLST" : "Liverpool Street",
            "OMAN" : "Mansion House",
            "MLE" : "Mile End",
            "OMON" : "Monument",
            "OMGT" : "Moorgate",
            "ONHG" : "Notting Hill Gate",
            "PADc" : "Paddington Circle",
            "PADs" : "Paddington H & C",
            "PLW" : "Plaistow",
            "ROA" : "Royal Oak",
            "OSSQ" : "Sloane Square",
            "OSKN" : "South Kensington",
            "OSJP" : "St. James's Park",
            "STG" : "Stepney Green",
            "OTEM" : "Temple",
            "OTHL" : "Tower Hill",
            "UPK" : "Upton Park",
            "OVIC" : "Victoria",
            "WHM" : "West Ham",
            "WBP" : "Westbourne Park",
            "OWMS" : "Westminster",
            "WCL" : "Whitechapel",

            # District

            "DACT" : "Acton Town",            
            "DALE" : "Aldgate East",
            "BKG" : "Barking",
            "BCT" : "Barons Court",
            "BEC" : "Becontree",
            "DBLF" : "Blackfriars",
            "BWR" : "Bow Road",
            "BBB" : "Bromley-by-Bow",
            "DCST" : "Cannon Street",
            "CHP" : "Chiswick Park",
            "DGE" : "Dagenham East",
            "DGH" : "Dagenham Heathway",
            "EBY" : "Ealing Broadway",
            "ECM" : "Ealing Common",
            "DECM" : "Ealing Common",            
            "ECT" : "Earls Court",
            "EHM" : "East Ham",
            "EPY" : "East Putney",
            "DERD" : "Edgware Road (H & C)",
            "EPK" : "Elm Park",
            "DEMB" : "Embankment",            
            "FBY" : "Fulham Broadway",
            "DGRD" : "Gloucester Road",
            "GUN" : "Gunnersbury",
            "HMD" : "Hammersmith (District and Picc)",
            "DHST" : "High Street Kensington",
            "HCH" : "Hornchurch",
            "KEW" : "Kew Gardens",
            "DMAN" : "Mansion House",
            "MLE" : "Mile End",
            "DMON" : "Monument",
            "OLY" : "Olympia",
            "PGR" : "Parsons Green",
            "PLW" : "Plaistow",
            "PUT" : "Putney Bridge",
            "RCP" : "Ravenscourt Park",
            "RMD" : "Richmond",
            "DSSQ" : "Sloane Square",
            "SFS" : "Southfields",
            "DSKN" : "South Kensington",
            "DSJP" : "St. James's Park",
            "STB" : "Stamford Brook",
            "STG" : "Stepney Green",
            "DTEM" : "Temple",
            "DTHL" : "Tower Hill",
            "TGR" : "Turnham Green",
            "UPM" : "Upminster",
            "UPB" : "Upminster Bridge",
            "UPY" : "Upney",
            "UPK" : "Upton Park",
            "DVIC" : "Victoria",
            "WBT" : "West Brompton",
            "WHM" : "West Ham",
            "WKN" : "West Kensington",
            "DWMS" : "Westminster",
            "WCL" : "Whitechapel",
            "WDN" : "Wimbledon",
            "WMP" : "Wimbledon Park",
            
            # Hammersmith and City

            "HALD" : "Aldgate",
            "HALE" : "Aldgate East",
            "HBST" : "Baker Street",            
            "HBAR" : "Barbican",
            "BKG" : "Barking",
            "HBAY" : "Bayswater",
            "HBLF" : "Blackfriars",
            "BWR" : "Bow Road",
            "BBB" : "Bromley-by-Bow",
            "HCST" : "Cannon Street",
            "EHM" : "East Ham",
            "ERD" : "Edgware Road (H & C)",
            "HEMB" : "Embankment",            
            "HESQ" : "Euston Square",
            "HFAR" : "Farringdon",
            "HGRD" : "Gloucester Road",
            "HGPS" : "Great Portland Street",
            "HMS" : "Hammersmith (Circle and H&C)",
            "HHST" : "High Street Kensington",
            "HKXX" : "King's Cross St. Pancras",
            "LBG" : "Ladbroke Grove",
            "HLST" : "Liverpool Street",
            "HMAN" : "Mansion House",
            "MLE" : "Mile End",
            "HMON" : "Monument",
            "HMGT" : "Moorgate",
            "HNHG" : "Notting Hill Gate",
            "PADc" : "Paddington Circle",
            "PADs" : "Paddington H & C",
            "PLW" : "Plaistow",
            "ROA" : "Royal Oak",
            "HSSQ" : "Sloane Square",
            "HSKN" : "South Kensington",
            "HSJP" : "St. James's Park",
            "STG" : "Stepney Green",
            "HTEM" : "Temple",
            "HTHL" : "Tower Hill",
            "UPK" : "Upton Park",
            "HVIC" : "Victoria",
            "WHM" : "West Ham",
            "WBP" : "Westbourne Park",
            "HWMS" : "Westminster",
            "WCL" : "Whitechapel",
            
            # Jubilee
            
            "JBST" : "Baker Street",            
            "BER" : "Bermondsey",
            "BDS" : "Bond Street",
            "CWR" : "Canada Water",
            "CWF" : "Canary Wharf",
            "CNT" : "Canning Town",
            "CPK" : "Canons Park",
            "CHX" : "Charing Cross",
            "DHL" : "Dollis Hill",
            "FRD" : "Finchley Road",
            "GPK" : "Green Park",
            "KIL" : "Kilburn",
            "KBY" : "Kingsbury",
            "LON" : "London Bridge",
            "NEA" : "Neasden",
            "NGW" : "North Greenwich",
            "QBY" : "Queensbury",
            "SWK" : "Southwark",
            "SJW" : "St. John's Wood",
            "STA" : "Stanmore",
            "SFD" : "Stratford",
            "SWC" : "Swiss Cottage",
            "WLO" : "Waterloo",
            "WPK" : "Wembley Park",
            "WHM" : "West Ham",
            "WHD" : "West Hampstead",
            "JWMS" : "Westminster",
            "WLG" : "Willesden Green",
            
            # Metropolitain
            
            "MALD" : "Aldgate",
            "AME" : "Amersham",
            "MBST" : "Baker Street",            
            "MBAR" : "Barbican",
            "CLF" : "Chalfont & Latimer",
            "CWD" : "Chorleywood",
            "CRX" : "Croxley",
            "ETE" : "Eastcote",
            "MESQ" : "Euston Square",
            "MFAR" : "Farringdon",
            "FRD" : "Finchley Road",
            "MGPS" : "Great Portland Street",
            "HOH" : "Harrow on the Hill",
            "HDN" : "Hillingdon",
            "ICK" : "Ickenham",
            "MKXX" : "King's Cross St. Pancras",
            "MLST" : "Liverpool Street",
            "MPK" : "Moor Park",
            "MMGT" : "Moorgate",
            "NHR" : "North Harrow",
            "NWP" : "Northwick Park",
            "NWD" : "Northwood",
            "NWH" : "Northwood Hills",
            "PIN" : "Pinner",
            "RLN" : "Rayners Lane",
            "MRLN" : "Rayners Lane",            
            "RKY" : "Rickmansworth",
            "RUI" : "Ruislip",
            "RUM" : "Ruislip Manor",
            "UXB" : "Uxbridge",
            "WAT" : "Watford",
            "WPK" : "Wembley Park",
            "WHR" : "West Harrow",
            "WCL" : "Whitechapel",
            "WSP" : "Woodside Park",
            
            # Northern
            
            "ANG" : "Angel",
            "ARC" : "Archway",
            "BAL" : "Balham",
            "NBNK" : "Bank",
            "BPK" : "Belsize Park",
            "BOR" : "Borough",
            "BTX" : "Brent Cross",
            "BUR" : "Burnt Oak",
            "CTN" : "Camden Town",
            "CHF" : "Chalk Farm",
            "CHX" : "Charing Cross",
            "CPC" : "Clapham Common",
            "CPN" : "Clapham North",
            "CPS" : "Clapham South",
            "COL" : "Colindale",
            "CLW" : "Colliers Wood",
            "EFY" : "East Finchley",
            "EDG" : "Edgware",
            "ELE" : "Elephant & Castle",
            "NEMB" : "Embankment",            
            "NEUS" : "Euston",
            "FYC" : "Finchley Central",
            "GGR" : "Golders Green",
            "GST" : "Goodge Street",
            "HMP" : "Hampstead",
            "HND" : "Hendon Central",
            "HBT" : "High Barnet",
            "HIG" : "Highgate",
            "KEN" : "Kennington",
            "KTN" : "Kentish Town",
            "NKXX" : "King's Cross St. Pancras",
            "LSQ" : "Leicester Square",
            "LON" : "London Bridge",
            "MHE" : "Mill Hill East",
            "NMGT" : "Moorgate",
            "MOR" : "Morden",
            "MCR" : "Mornington Crescent",
            "OLD" : "Old Street",
            "OVL" : "Oval",
            "SWM" : "South Wimbledon",
            "STK" : "Stockwell",
            "TBE" : "Tooting Bec",
            "TBY" : "Tooting Broadway",
            "TCR" : "Tottenham Court Road",
            "TOT" : "Totteridge and Whetstone",
            "TPK" : "Tufnell Park",
            "WST" : "Warren Street",
            "WLO" : "Waterloo",
            "WFY" : "West Finchley",
            "WSP" : "Woodside Park",                
            
            # Piccadilly
            
            "PACT" : "Acton Town",            
            "ALP" : "Alperton",
            "AGR" : "Arnos Grove",
            "ARL" : "Arsenal",
            "BCT" : "Barons Court",
            "BOS" : "Boston Manor",
            "BGR" : "Bounds Green",
            "CRD" : "Caledonian Road",
            "CFS" : "Cockfosters",
            "COV" : "Covent Garden",
            "ECM" : "Ealing Common",
            "PECM" : "Ealing Common",            
            "ECT" : "Earls Court",
            "ETE" : "Eastcote",
            "PFPK" : "Finsbury Park",
            "PGRD" : "Gloucester Road",
            "GPK" : "Green Park",
            "HMD" : "Hammersmith (District and Picc)",
            "HTX" : "Hatton Cross",
            "HRF" : "Heathrow Terminal 4",
            "HRV" : "Heathrow Terminal 5",
            "HRC" : "Heathrow Terminals 123",
            "HDN" : "Hillingdon",
            "HOL" : "Holborn",
            "HRD" : "Holloway Road",
            "HNC" : "Hounslow Central",
            "HNE" : "Hounslow East",
            "HNW" : "Hounslow West",
            "HPC" : "Hyde Park Corner",
            "ICK" : "Ickenham",
            "PKXX" : "King's Cross St. Pancras",
            "KNB" : "Knightsbridge",
            "LSQ" : "Leicester Square",
            "MNR" : "Manor House",
            "NEL" : "North Ealing",
            "NFD" : "Northfields",
            "OAK" : "Oakwood",
            "OST" : "Osterley",
            "PRY" : "Park Royal",
            "PIC" : "Piccadilly Circus",
            "RLN" : "Rayners Lane",
            "PRLN" : "Rayners Lane",            
            "RUI" : "Ruislip",
            "RUM" : "Ruislip Manor",
            "RSQ" : "Russell Square",
            "SEL" : "South Ealing",
            "SHR" : "South Harrow",
            "PSKN" : "South Kensington",
            "SGT" : "Southgate",
            "SHL" : "Sudbury Hill",
            "STN" : "Sudbury Town",
            "TGR" : "Turnham Green",
            "TPL" : "Turnpike Lane",
            "UXB" : "Uxbridge",
            "WGN" : "Wood Green",
            
            # Victoria
            
            "VBHR" : "Blackhorse Road",
            "BRX" : "Brixton",
            "VEUS" : "Euston",
            "VFPK" : "Finsbury Park",
            "GPK" : "Green Park",
            "HBY" : "Highbury & Islington",
            "VKXX" : "King's Cross St. Pancras",
            "VOXC" : "Oxford Circus",
            "PIM" : "Pimlico",
            "SVS" : "Seven Sisters",
            "STK" : "Stockwell",
            "TTH" : "Tottenham Hale",
            "VUX" : "Vauxhall",
            "VVIC" : "Victoria",
            "WAL" : "Walthamstow Central",
            "WST" : "Warren Street",                
            
            # Waterloo and City
            
            "WBNK" : "Bank",
            "WLO" : "Waterloo",
            
            # DLR
            
            "als" : "All Saints",
            "ban" : "Bank",
            "bec" : "Beckton",
            "bep" : "Beckton Park",
            "bla" : "Blackwall",
            "boc" : "Bow Church",
            "caw" : "Canary Wharf",
            "cat" : "Canning Town",
            "cro" : "Crossharbour",
            "cuh" : "Custom House",
            "cus" : "Cutty Sark",
            "cyp" : "Cyprus",
            "deb" : "Deptford Bridge",
            "der" : "Devons Road",
            "eai" : "East India",
            "elr" : "Elverson Road",
            "gar" : "Gallions Reach",
            "gre" : "Greenwich",
            "heq" : "Heron Quays",
            "isg" : "Island Gardens",
            "kgv" : "King George V",
            "lew" : "Lewisham",
            "lim" : "Limehouse",
            "lca" : "London City Airport",
            "mud" : "Mudchute",
            "pop" : "Poplar",
            "pdk" : "Pontoon Dock",
            "prr" : "Prince Regent",
            "pml" : "Pudding Mill Lane",
            "roa" : "Royal Albert",
            "rov" : "Royal Victoria",
            "sha" : "Shadwell",
            "soq" : "South Quay",
            "str" : "Stratford",
            "tog" : "Tower Gateway",
            "wes" : "Westferry",
            "wiq" : "West India Quay",
            "wst" : "West Silvertown",
            "woa" : "Woolwich Arsenal",

            # River Service...uh?
            
            }

class getinfo (api) :

    def get (self, code) :

        if not self.stations.has_key(code) :
            self.api_error(404, 'Station not found')
            return

        linecode = 'FIXME'
        
        url = "http://www.tfl.gov.uk/tfl/livetravelnews/departureboards/tube/default.asp?LineCode=%s&StationCode=%s" % (linecode, code)
        
        out = {
            'code' : code,
            'service' : 'tfl',
            'name' :  { '_content' : self.stations[code] },
            'url' : { '_content' : url },
            }
        
        self.api_ok({'station' : out})
        return        
