# HEY LOOK! THIS IS STILL FULL OF INCOMPLETENESS!!

import fakesubwayapis

class ukrail :

    def __init__ (self) :
        
        # http://www.nationalrail.co.uk/stations/codes/
        
        self.stations = {
            "ABW" : "Abbey Wood",
            "ABE" : "Aber",
            "ACY" : "Abercynon",
            "ABA" : "Aberdare",
            "ABD" : "Aberdeen",
            "AUR" : "Aberdour",
            "AVY" : "Aberdovey",
            "ABH" : "Abererch",
            "AGV" : "Abergavenny",
            "AGL" : "Abergele & Pensarn",
            "AYL" : "Aberystwyth",
            "ACR" : "Accrington",
            "AAT" : "Achanalt",
            "ACN" : "Achnasheen",
            "ACH" : "Achnashellach",
            "ACK" : "Acklington",
            "ACL" : "Acle",
            "ACG" : "Acocks Green",
            "ACB" : "Acton Bridge",
            "ACC" : "Acton Central",
            "AML" : "Acton Main Line",
            "ADD" : "Adderley Park",
            "ADW" : "Addiewell",
            "ASN" : "Addlestone",
            "ADM" : "Adisham",
            "ADC" : "Adlington (Cheshire)",
            "ADL" : "Adlington (Lancs)",
            "AWK" : "Adwick",
            "AIG" : "Aigburth",
            "ANS" : "Ainsdale",
            "AIN" : "Aintree",
            "AIR" : "Airbles",
            "ADR" : "Airdrie",
            "AYP" : "Albany Park",
            "ALB" : "Albrighton",
            "ALD" : "Alderley Edge",
            "AMT" : "Aldermaston",
            "AHT" : "Aldershot",
            "AGT" : "Aldrington",
            "AAP" : "Alexandra Palace",
            "AXP" : "Alexandra Parade",
            "ALX" : "Alexandria",
            "ALF" : "Alfreton",
            "ALW" : "Allens West",
            "ALO" : "Alloa",
            "ASS" : "Alness",
            "ALM" : "Alnmouth",
            "ALR" : "Alresford",
            "ASG" : "Alsager",
            "ALN" : "Althorne",
            "ALP" : "Althorpe",
            "ABC" : "Altnabreac",
            "AON" : "Alton",
            "ALT" : "Altrincham",
            "ALV" : "Alvechurch",
            "AMB" : "Ambergate",
            "AMY" : "Amberley",
            "AMR" : "Amersham",
            "AMF" : "Ammanford",
            "ANC" : "Ancaster",
            "AND" : "Anderston",
            "ADV" : "Andover",
            "ANZ" : "Anerley",
            "AGR" : "Angel Road",
            "ANG" : "Angmering",
            "ANN" : "Annan",
            "ANL" : "Anniesland",
            "AFV" : "Ansdell & Fairhaven",
            "APP" : "Appleby",
            "APD" : "Appledore (Kent)",
            "APF" : "Appleford",
            "APB" : "Appley Bridge",
            "APS" : "Apsley",
            "ARB" : "Arbroath",
            "ARD" : "Ardgay",
            "AUI" : "Ardlui",
            "ADS" : "Ardrossan Harbour",
            "ASB" : "Ardrossan South Beach",
            "ADN" : "Ardrossan Town",
            "ADK" : "Ardwick",
            "AGS" : "Argyle Street",
            "ARG" : "Arisaig",
            "ARL" : "Arlesey",
            "AWT" : "Armathwaite",
            "ARN" : "Arnside",
            "ARR" : "Arram",
            "ART" : "Arrochar & Tarbet",
            "ARU" : "Arundel",
            "ACT" : "Ascot",
            "AUW" : "Ascott-under-Wychwood",
            "ASH" : "Ash",
            "AHV" : "Ash Vale",
            "ABY" : "Ashburys",
            "ASC" : "Ashchurch for Tewkesbury",
            "ASF" : "Ashfield",
            "AFK" : "Ashford International",
            "ASI" : "Ashford International (Eurostar)",
            "AFS" : "Ashford (Surrey)",
            "ASY" : "Ashley",
            "AHD" : "Ashtead",
            "AHN" : "Ashton-under-Lyne",
            "AHS" : "Ashurst",
            "ANF" : "Ashurst New Forest",
            "AWM" : "Ashwell & Morden",
            "ASK" : "Askam",
            "ALK" : "Aslockton",
            "ASP" : "Aspatria",
            "APG" : "Aspley Guise",
            "AST" : "Aston",
            "ATH" : "Atherstone",
            "ATN" : "Atherton",
            "ATT" : "Attadale",
            "ATB" : "Attenborough",
            "ATL" : "Attleborough",
            "AUK" : "Auchinleck",
            "AUD" : "Audley End",
            "AUG" : "Aughton Park",
            "AVM" : "Aviemore",
            "AVF" : "Avoncliff",
            "AVN" : "Avonmouth",
            "AXM" : "Axminster",
            "AYS" : "Aylesbury",
            "AVP" : "Aylesbury Vale Parkway",
            "AYL" : "Aylesford",
            "AYH" : "Aylesham",
            "AYR" : "Ayr",
            "BAC" : "Bache",
            "BAJ" : "Baglan",
            "BAG" : "Bagshot",
            "BLD" : "Baildon",
            "BIO" : "Baillieston",
            "BAB" : "Balcombe",
            "BDK" : "Baldock",
            "BAL" : "Balham",
            "BHC" : "Balloch",
            "BSI" : "Balmossie",
            "BMB" : "Bamber Bridge",
            "BAM" : "Bamford",
            "BNV" : "Banavie",
            "BAN" : "Banbury",
            "BNG" : "Bangor (Gwynedd)",
            "BAH" : "Bank Hall",
            "BAD" : "Banstead",
            "BSS" : "Barassie",
            "ZBB" : "Barbican",
            "BLL" : "Bardon Mill",
            "BAR" : "Bare Lane",
            "BGI" : "Bargeddie",
            "BGD" : "Bargoed",
            "BKG" : "Barking",
            "ZBK" : "Barking Underground",
            "BRT" : "Barlaston",
            "BMG" : "Barming",
            "BRM" : "Barmouth",
            "BNH" : "Barnehurst",
            "BNS" : "Barnes",
            "BNI" : "Barnes Bridge",
            "BTB" : "Barnetby",
            "BAA" : "Barnham",
            "BNL" : "Barnhill",
            "BNY" : "Barnsley",
            "BNP" : "Barnstaple",
            "BTG" : "Barnt Green",
            "BRR" : "Barrhead",
            "BRL" : "Barrhill",
            "BAV" : "Barrow Haven",
            "BWS" : "Barrow Upon Soar",
            "BIF" : "Barrow-in-Furness",
            "BRY" : "Barry",
            "BYD" : "Barry Docks",
            "BYI" : "Barry Island",
            "BYL" : "Barry Links",
            "BAU" : "Barton-on-Humber",
            "BSO" : "Basildon",
            "BSK" : "Basingstoke",
            "BBL" : "Bat & Ball",
            "BTH" : "Bath Spa",
            "BHG" : "Bathgate",
            "BTL" : "Batley",
            "BTT" : "Battersby",
            "BAK" : "Battersea Park",
            "BAT" : "Battle",
            "BLB" : "Battlesbridge",
            "BAY" : "Bayford",
            "BCF" : "Beaconsfield",
            "BER" : "Bearley",
            "BRN" : "Bearsden",
            "BSD" : "Bearsted",
            "BSL" : "Beasdale",
            "BEU" : "Beaulieu Road",
            "BEL" : "Beauly",
            "BEB" : "Bebington",
            "BCC" : "Beccles",
            "BEC" : "Beckenham Hill",
            "BKJ" : "Beckenham Junction",
            "BDM" : "Bedford",
            "BSJ" : "Bedford St Johns",
            "BDH" : "Bedhampton",
            "BMT" : "Bedminster",
            "BEH" : "Bedworth",
            "BDW" : "Bedwyn",
            "BEE" : "Beeston",
            "BKS" : "Bekesbourne",
            "BLV" : "Belle Vue",
            "BLG" : "Bellgrove",
            "BGM" : "Bellingham",
            "BLH" : "Bellshill",
            "BLM" : "Belmont",
            "BLP" : "Belper",
            "BEG" : "Beltring",
            "BVD" : "Belvedere",
            "BEM" : "Bempton",
            "BEY" : "Ben Rhydding",
            "BEF" : "Benfleet",
            "BEN" : "Bentham",
            "BTY" : "Bentley",
            "BYK" : "Bentley (South Yorks)",
            "BAS" : "Bere Alston",
            "BFE" : "Bere Ferrers",
            "BKM" : "Berkhamsted",
            "BKW" : "Berkswell",
            "BYA" : "Berney Arms",
            "BBW" : "Berry Brow",
            "BRS" : "Berrylands",
            "BRK" : "Berwick",
            "BWK" : "Berwick-upon-Tweed",
            "BES" : "Bescar Lane",
            "BSC" : "Bescot Stadium",
            "BTO" : "Betchworth",
            "BET" : "Bethnal Green",
            "BYC" : "Betws-y-Coed",
            "BEV" : "Beverley",
            "BEX" : "Bexhill",
            "BXY" : "Bexley",
            "BXH" : "Bexleyheath",
            "BCS" : "Bicester North",
            "BIT" : "Bicester Town",
            "BKL" : "Bickley",
            "BID" : "Bidston",
            "BIW" : "Biggleswade",
            "BBK" : "Bilbrook",
            "BIC" : "Billericay",
            "BIL" : "Billingham",
            "BIG" : "Billingshurst",
            "BIN" : "Bingham",
            "BIY" : "Bingley",
            "BCG" : "Birchgrove",
            "BCH" : "Birchington-on-sea",
            "BWD" : "Birchwood",
            "BIK" : "Birkbeck",
            "BDL" : "Birkdale",
            "BKC" : "Birkenhead Central",
            "BKN" : "Birkenhead North",
            "BKP" : "Birkenhead Park",
            "BHI" : "Birmingham International",
            "BMO" : "Birmingham Moor Street",
            "BHM" : "Birmingham New Street",
            "BSW" : "Birmingham Snow Hill",
            "BIA" : "Bishop Auckland",
            "BBG" : "Bishopbriggs",
            "BIS" : "Bishops Stortford",
            "BIP" : "Bishopstone",
            "BPT" : "Bishopton",
            "BTE" : "Bitterne",
            "BBN" : "Blackburn",
            "BKH" : "Blackheath",
            "BHO" : "Blackhorse Road",
            "BPN" : "Blackpool North",
            "BPB" : "Blackpool Pleasure Beach",
            "BPS" : "Blackpool South",
            "BLK" : "Blackrod",
            "BAW" : "Blackwater",
            "BFF" : "Blaenau Ffestiniog",
            "BLA" : "Blair Atholl",
            "BAI" : "Blairhill",
            "BKT" : "Blake Street",
            "BKD" : "Blakedown",
            "BLT" : "Blantyre",
            "BLO" : "Blaydon",
            "BSB" : "Bleasby",
            "BLY" : "Bletchley",
            "BLX" : "Bloxwich",
            "BWN" : "Bloxwich North",
            "BLN" : "Blundellsands & Crosby",
            "BYB" : "Blythe Bridge",
            "BOD" : "Bodmin Parkway",
            "BOR" : "Bodorgan",
            "BOG" : "Bognor Regis",
            "BGS" : "Bogston",
            "BON" : "Bolton",
            "BTD" : "Bolton-on-Dearne",
            "BKA" : "Bookham",
            "BOC" : "Bootle",
            "BNW" : "Bootle New Strand",
            "BOT" : "Bootle Oriel Road",
            "BBS" : "Bordesley",
            "BRG" : "Borough Green & Wrotham",
            "BRH" : "Borth",
            "BOH" : "Bosham",
            "BSN" : "Boston",
            "BOE" : "Botley",
            "BTF" : "Bottesford",
            "BNE" : "Bourne End",
            "BMH" : "Bournemouth",
            "BRV" : "Bournville",
            "BWB" : "Bow Brickhill",
            "BOP" : "Bowes Park",
            "BWG" : "Bowling",
            "BXW" : "Boxhill & Westhumble",
            "BCE" : "Bracknell",
            "BDQ" : "Bradford Forster Square",
            "BDI" : "Bradford Interchange",
            "BOA" : "Bradford-on-Avon",
            "BDN" : "Brading",
            "BTR" : "Braintree",
            "BTP" : "Braintree Freeport",
            "BML" : "Bramhall",
            "BLE" : "Bramley",
            "BMY" : "Bramley (Hants)",
            "BMP" : "Brampton (Cumbria)",
            "BRP" : "Brampton (Suffolk)",
            "BCN" : "Branchton",
            "BND" : "Brandon",
            "BSM" : "Branksome",
            "BYS" : "Braystones",
            "BDY" : "Bredbury",
            "BRC" : "Breich",
            "BFD" : "Brentford",
            "BRE" : "Brentwood",
            "BWO" : "Bricket Wood",
            "BEA" : "Bridge of Allan",
            "BRO" : "Bridge of Orchy",
            "BGN" : "Bridgend",
            "BDG" : "Bridgeton",
            "BWT" : "Bridgwater",
            "BDT" : "Bridlington",
            "BRF" : "Brierfield",
            "BGG" : "Brigg",
            "BGH" : "Brighouse",
            "BTN" : "Brighton",
            "BMD" : "Brimsdown",
            "BNT" : "Brinnington",
            "BPW" : "Bristol Parkway",
            "BRI" : "Bristol Temple Meads",
            "BHD" : "Brithdir",
            "RBS" : "British Steel Redcar",
            "BNF" : "Briton Ferry",
            "BRX" : "Brixton",
            "BGE" : "Broad Green",
            "BDB" : "Broadbottom",
            "BSR" : "Broadstairs",
            "BCU" : "Brockenhurst",
            "BHS" : "Brockholes",
            "BCY" : "Brockley",
            "BOM" : "Bromborough",
            "BMR" : "Bromborough Rake",
            "BMC" : "Bromley Cross",
            "BMN" : "Bromley North",
            "BMS" : "Bromley South",
            "BMV" : "Bromsgrove",
            "BSY" : "Brondesbury",
            "BSP" : "Brondesbury Park",
            "BPK" : "Brookmans Park",
            "BKO" : "Brookwood",
            "BME" : "Broome",
            "BMF" : "Broomfleet",
            "BRA" : "Brora",
            "BUH" : "Brough",
            "BYF" : "Broughty Ferry",
            "BXB" : "Broxbourne",
            "BCV" : "Bruce Grove",
            "BDA" : "Brundall",
            "BGA" : "Brundall Gardens",
            "BSU" : "Brunstane",
            "BRW" : "Brunswick",
            "BRU" : "Bruton",
            "BYN" : "Bryn",
            "BUC" : "Buckenham",
            "BCK" : "Buckley",
            "BUK" : "Bucknell",
            "BGL" : "Bugle",
            "BHR" : "Builth Road",
            "BLW" : "Bulwell",
            "BUE" : "Bures",
            "BUG" : "Burgess Hill",
            "BUY" : "Burley Park",
            "BUW" : "Burley-in-Wharfedale",
            "BNA" : "Burnage",
            "BUD" : "Burneside",
            "BNM" : "Burnham",
            "BUU" : "Burnham-on-Crouch",
            "BUB" : "Burnley Barracks",
            "BNC" : "Burnley Central",
            "BYM" : "Burnley Manchester Road",
            "BUI" : "Burnside",
            "BTS" : "Burntisland",
            "BCB" : "Burscough Bridge",
            "BCJ" : "Burscough Junction",
            "BUO" : "Bursledon",
            "BUJ" : "Burton Joyce",
            "BUT" : "Burton-on-Trent",
            "BSE" : "Bury St Edmunds",
            "BUS" : "Busby",
            "BHK" : "Bush Hill Park",
            "BSH" : "Bushey",
            "BUL" : "Butlers Lane",
            "BXD" : "Buxted",
            "BUX" : "Buxton",
            "BFN" : "Byfleet & New Haw",
            "BYE" : "Bynea",
            "CAD" : "Cadoxton",
            "CGW" : "Caergwrle",
            "CPH" : "Caerphilly",
            "CWS" : "Caersws",
            "CDT" : "Caldicot",
            "" : "C",
            "CSK" : "Calstock",
            "" : "C",
            "CAM" : "Camberley",
            "CBN" : "Camborne",
            "CBG" : "Cambridge",
            "CBH" : "Cambridge Heath",
            "CBL" : "Cambuslang",
            "CMD" : "Camden Road",
            "CMO" : "Camelon",
            "CNL" : "Canley",
            "CAO" : "Cannock",
            "CNN" : "Canonbury",
            "CBE" : "Canterbury East",
            "CBW" : "Canterbury West",
            "CNY" : "Cantley",
            "CPU" : "Capenhurst",
            "CBB" : "Carbis Bay",
            "CDD" : "Cardenden",
            "CDB" : "Cardiff Bay",
            "CDF" : "Cardiff Central",
            "CDQ" : "Cardiff Queen Street",
            "CDO" : "Cardonald",
            "CDR" : "Cardross",
            "CRF" : "Carfin",
            "CAK" : "Cark",
            "CAR" : "Carlisle",
            "CTO" : "Carlton",
            "CLU" : "Carluke",
            "CMN" : "Carmarthen",
            "CML" : "Carmyle",
            "CNF" : "Carnforth",
            "CAN" : "Carnoustie",
            "CAY" : "Carntyne",
            "CPK" : "Carpenders Park",
            "CAG" : "Carrbridge",
            "CSH" : "Carshalton",
            "CSB" : "Carshalton Beeches",
            "CRS" : "Carstairs",
            "CDY" : "Cartsdyke",
            "CBP" : "Castle Bar Park",
            "CLC" : "Castle Cary",
            "CFD" : "Castleford",
            "CAS" : "Castleton",
            "CSM" : "Castleton Moor",
            "CAT" : "Caterham",
            "CTF" : "Catford",
            "CFB" : "Catford Bridge",
            "CYS" : "Cathays",
            "CCT" : "Cathcart",
            "CTL" : "Cattal",
            "CAU" : "Causeland",
            "" : "C",
            "CTH" : "Chadwell Heath",
            "CFH" : "Chafford Hundred",
            "" : "C",
            "CHW" : "Chalkwell",
            "CFR" : "Chandlers Ford",
            "" : "C",
            "CPN" : "Chapelton",
            "CLN" : "Chapeltown",
            "" : "C",
            "CHG" : "Charing",
            "" : "C",
            "CBY" : "Charlbury",
            "CTN" : "Charlton",
            "CRT" : "Chartham",
            "CSR" : "Chassen Road",
            "CTE" : "Chatelherault",
            "CTM" : "Chatham",
            "CHT" : "Chathill",
            "CHU" : "Cheadle Hulme",
            "CHE" : "Cheam",
            "CED" : "Cheddington",
            "CEL" : "Chelford",
            "CHM" : "Chelmsford",
            "CLD" : "Chelsfield",
            "CNM" : "Cheltenham Spa",
            "CPW" : "Chepstow",
            "CYT" : "Cherry Tree",
            "CHY" : "Chertsey",
            "CHN" : "Cheshunt",
            "CSN" : "Chessington North",
            "CSS" : "Chessington South",
            "CTR" : "Chester",
            "CRD" : "Chester Road",
            "CHD" : "Chesterfield",
            "" : "C",
            "" : "C",
            "CNO" : "Chetnole",
            "CCH" : "Chichester",
            "CIL" : "Chilham",
            "CHL" : "Chilworth",
            "CHI" : "Chingford",
            "CLY" : "Chinley",
            "CPM" : "Chippenham",
            "CHP" : "Chipstead",
            "CRK" : "Chirk",
            "CIT" : "Chislehurst",
            "CHK" : "Chiswick",
            "CHO" : "Cholsey",
            "CRL" : "Chorley",
            "CLW" : "Chorleywood",
            "CHR" : "Christchurch",
            "CHH" : "Christs Hospital",
            "" : "C",
            "CHF" : "Church Fenton",
            "CTT" : "Church Stretton",
            "CIM" : "Cilmeri",
            "CTK" : "City Thameslink",
            "CLT" : "Clacton on Sea",
            "CLA" : "Clandon",
            "CLP" : "Clapham High Street",
            "CLJ" : "Clapham Junction",
            "" : "C",
            "CPT" : "Clapton",
            "CLR" : "Clarbeston Road",
            "CKS" : "Clarkston",
            "CLV" : "Claverdon",
            "CLG" : "Claygate",
            "CLE" : "Cleethorpes",
            "CEA" : "Cleland",
            "CLI" : "Clifton",
            "CFN" : "Clifton Down",
            "CLH" : "Clitheroe",
            "CLK" : "Clock House",
            "CUW" : "Clunderwen",
            "CYK" : "Clydebank",
            "CBC" : "Coatbridge Central",
            "CBS" : "Coatbridge Sunnyside",
            "COA" : "Coatdyke",
            "" : "C",
            "CSL" : "Codsall",
            "CGN" : "Cogan",
            "COL" : "Colchester",
            "CET" : "Colchester Town",
            "CEH" : "Coleshill Parkway",
            "CLM" : "Collingham",
            "CLL" : "Collington",
            "CNE" : "Colne",
            "CWL" : "Colwall",
            "CWB" : "Colwyn Bay",
            "CME" : "Combe",
            "COM" : "Commondale",
            "CNG" : "Congleton",
            "CNS" : "Conisbrough",
            "CON" : "Connel Ferry",
            "CEY" : "Cononley",
            "CNP" : "Conway Park",
            "CNW" : "Conwy",
            "COB" : "Cooden Beach",
            "COO" : "Cookham",
            "CBR" : "Cooksbridge",
            "COE" : "Coombe Junction Halt",
            "COP" : "Copplestone",
            "CRB" : "Corbridge",
            "COR" : "Corby",
            "CKH" : "Corkerhill",
            "CKL" : "Corkickle",
            "CPA" : "Corpach",
            "CRR" : "Corrour",
            "COY" : "Coryton",
            "CSY" : "Coseley",
            "COS" : "Cosford",
            "CSA" : "Cosham",
            "CGM" : "Cottingham",
            "COT" : "Cottingley",
            "CDS" : "Coulsdon South",
            "COV" : "Coventry",
            "CWN" : "Cowden",
            "COW" : "Cowdenbeath",
            "CRA" : "Cradley Heath",
            "CGD" : "Craigendoran",
            "CRM" : "Cramlington",
            "CRV" : "Craven Arms",
            "CRW" : "Crawley",
            "CRY" : "Crayford",
            "CDI" : "Crediton",
            "CES" : "Cressing",
            "CSG" : "Cressington",
            "CWD" : "Creswell",
            "CRE" : "Crewe",
            "CKN" : "Crewkerne",
            "CWH" : "Crews Hill",
            "CNR" : "Crianlarich",
            "CCC" : "Criccieth",
            "CRI" : "Cricklewood",
            "CFF" : "Croftfoot",
            "CFT" : "Crofton Park",
            "CMR" : "Cromer",
            "CMF" : "Cromford",
            "CKT" : "Crookston",
            "CRG" : "Cross Gates",
            "CFL" : "Crossflatts",
            "COI" : "Crosshill",
            "CKY" : "Crosskeys",
            "CMY" : "Crossmyloof",
            "CSO" : "Croston",
            "CRH" : "Crouch Hill",
            "COH" : "Crowborough",
            "CWU" : "Crowhurst",
            "CWE" : "Crowle",
            "CRN" : "Crowthorne",
            "CRO" : "Croy",
            "CYP" : "Crystal Palace",
            "CUD" : "Cuddington",
            "CUF" : "Cuffley",
            "CUM" : "Culham",
            "CUA" : "Culrain",
            "CUB" : "Cumbernauld",
            "CUP" : "Cupar",
            "CUH" : "Curriehill",
            "CUX" : "Cuxton",
            "CMH" : "Cwmbach",
            "CWM" : "Cwmbran",
            "CYN" : "Cynghordy",
            "DDK" : "Dagenham Dock",
            "DSY" : "Daisy Hill",
            "DAG" : "Dalgety Bay",
            "DAL" : "Dalmally",
            "DAK" : "Dalmarnock",
            "DAM" : "Dalmeny",
            "DMR" : "Dalmuir",
            "DLR" : "Dalreoch",
            "DLY" : "Dalry",
            "DLS" : "Dalston",
            "DLK" : "Dalston Kingsland",
            "DLT" : "Dalton",
            "DLW" : "Dalwhinnie",
            "DNY" : "Danby",
            "DCT" : "Danescourt",
            "DZY" : "Danzey",
            "DAR" : "Darlington",
            "DAN" : "Darnall",
            "DSM" : "Darsham",
            "DFD" : "Dartford",
            "DRT" : "Darton",
            "DWN" : "Darwen",
            "DAT" : "Datchet",
            "DVN" : "Davenport",
            "DWL" : "Dawlish",
            "DWW" : "Dawlish Warren",
            "DEA" : "Deal",
            "DEN" : "Dean",
            "DNN" : "Dean Lane",
            "DGT" : "Deansgate",
            "DGY" : "Deganwy",
            "DHN" : "Deighton",
            "DLM" : "Delamere",
            "DBD" : "Denby Dale",
            "DNM" : "Denham",
            "DGC" : "Denham Golf Club",
            "DMK" : "Denmark Hill",
            "DNT" : "Dent",
            "DTN" : "Denton",
            "DEP" : "Deptford",
            "DBY" : "Derby",
            "DBR" : "Derby Road",
            "DKR" : "Derker",
            "DPT" : "Devonport",
            "DEW" : "Dewsbury",
            "DID" : "Didcot Parkway",
            "" : "D",
            "DMH" : "Dilton Marsh",
            "" : "",
            "" : "D",
            "DGL" : "Dingle Road",
            "DIN" : "Dingwall",
            "DND" : "Dinsdale",
            "DTG" : "Dinting",
            "DSL" : "Disley",
            "DIS" : "Diss",
            "DOC" : "Dockyard",
            "DOD" : "Dodworth",
            "DOL" : "Dolau",
            "DLH" : "Doleham",
            "DLG" : "Dolgarrog",
            "DWD" : "Dolwyddelan",
            "DON" : "Doncaster",
            "DCH" : "Dorchester South",
            "DCW" : "Dorchester West",
            "DOR" : "Dore",
            "DKG" : "Dorking",
            "DPD" : "Dorking Deepdene",
            "DKT" : "Dorking West",
            "DMS" : "Dormans",
            "DDG" : "Dorridge",
            "DVH" : "Dove Holes",
            "DVP" : "Dover Priory",
            "DVC" : "Dovercourt",
            "DVY" : "Dovey Junction",
            "DOW" : "Downham Market",
            "DRG" : "Drayton Green",
            "DYP" : "Drayton Park",
            "DRM" : "Drem",
            "DRF" : "Driffield",
            "DRI" : "Drigg",
            "DTW" : "Droitwich Spa",
            "DRO" : "Dronfield",
            "DMC" : "Drumchapel",
            "DFR" : "Drumfrochar",
            "DRU" : "Drumgelloch",
            "DMY" : "Drumry",
            "DFP" : "Dublin Ferryport",
            "" : "D",
            "DUD" : "Duddeston",
            "DDP" : "Dudley Port",
            "DFI" : "Duffield",
            "DRN" : "Duirinish",
            "DST" : "Duke Street",
            "DUL" : "Dullingham",
            "DBC" : "Dumbarton Central",
            "DBE" : "Dumbarton East",
            "DUM" : "Dumbreck",
            "DMF" : "Dumfries",
            "DMP" : "Dumpton Park",
            "DUN" : "Dunbar",
            "DBL" : "Dunblane",
            "DCG" : "Duncraig",
            "DEE" : "Dundee",
            "DFL" : "Dunfermline Queen Margaret",
            "DFE" : "Dunfermline Town",
            "" : "D",
            "DNL" : "Dunlop",
            "DNO" : "Dunrobin Castle",
            "DOT" : "Dunston",
            "DNG" : "Dunton Green",
            "DHM" : "Durham",
            "" : "D",
            "DYC" : "Dyce",
            "DYF" : "Dyffryn Ardudwy",
            "EAG" : "Eaglescliffe",
            "EAL" : "Ealing Broadway",
            "ERL" : "Earlestown",
            "EAR" : "Earley",
            "EAD" : "Earlsfield",
            "" : "E",
            "" : "E",
            "ECR" : "East Croydon",
            "EDY" : "East Didsbury",
            "EDW" : "East Dulwich",
            "EFL" : "East Farleigh",
            "EGF" : "East Garforth",
            "EGR" : "East Grinstead",
            "EKL" : "East Kilbride",
            "EML" : "East Malling",
            "EMD" : "East Midlands Parkway",
            "ETL" : "East Tilbury",
            "EWR" : "East Worthing",
            "EBN" : "Eastbourne",
            "EBK" : "Eastbrook",
            "EST" : "Easterhouse",
            "ERA" : "Eastham Rake",
            "ESL" : "Eastleigh",
            "EGN" : "Eastrington",
            "EBD" : "Ebbsfleet International Domestic",
            "EBV" : "Ebbw Vale Parkway",
            "ECC" : "Eccles",
            "ECS" : "Eccles Road",
            "ECL" : "Eccleston Park",
            "EDL" : "Edale",
            "EDN" : "Eden Park",
            "EBR" : "Edenbridge",
            "EBT" : "Edenbridge Town",
            "EDG" : "Edge Hill",
            "EDP" : "Edinburgh Park",
            "EDB" : "Edinburgh Waverley",
            "EDR" : "Edmonton Green",
            "EFF" : "Effingham Junction",
            "EGG" : "Eggesford",
            "EGH" : "Egham",
            "EGT" : "Egton",
            "" : "E",
            "ELG" : "Elgin",
            "ELP" : "Ellesmere Port",
            "ELE" : "Elmers End",
            "ESD" : "Elmstead Woods",
            "ESW" : "Elmswell",
            "ELR" : "Elsecar",
            "ESM" : "Elsenham",
            "" : "E",
            "ELW" : "Eltham",
            "" : "E",
            "ELY" : "Ely",
            "EMP" : "Emerson Park",
            "EMS" : "Emsworth",
            "ENC" : "Enfield Chase",
            "ENL" : "Enfield Lock",
            "ENF" : "Enfield Town",
            "ENT" : "Entwistle",
            "EPS" : "Epsom",
            "EPD" : "Epsom Downs",
            "ERD" : "Erdington",
            "ERI" : "Eridge",
            "ERH" : "Erith",
            "ESH" : "Esher",
            "EXR" : "Essex Road",
            "ETC" : "Etchingham",
            "EBA" : "Euxton Balshaw Lane",
            "EVE" : "Evesham",
            "EWE" : "Ewell East",
            "EWW" : "Ewell West",
            "EXC" : "Exeter Central",
            "" : "E",
            "EXT" : "Exeter St Thomas",
            "EXG" : "Exhibition Centre",
            "EXM" : "Exmouth",
            "EXN" : "Exton",
            "EYN" : "Eynsford",
            "FLS" : "Failsworth",
            "FRB" : "Fairbourne",
            "FRF" : "Fairfield",
            "FRL" : "Fairlie",
            "FRW" : "Fairwater",
            "FCN" : "Falconwood",
            "FKG" : "Falkirk Grahamston",
            "FKK" : "Falkirk High",
            "FOC" : "Falls of Cruachan",
            "FMR" : "Falmer",
            "FAL" : "Falmouth Docks",
            "FMT" : "Falmouth Town",
            "FRM" : "Fareham",
            "" : "F",
            "FNN" : "Farnborough North",
            "FNC" : "Farncombe",
            "FNH" : "Farnham",
            "FNR" : "Farningham Road",
            "FNW" : "Farnworth",
            "ZFD" : "Farringdon",
            "FLD" : "Fauldhouse",
            "FAV" : "Faversham",
            "FGT" : "Faygate",
            "FAZ" : "Fazakerley",
            "FRN" : "Fearn",
            "FEA" : "Featherstone",
            "FLX" : "Felixstowe",
            "FEL" : "Feltham",
            "FNT" : "Feniton",
            "FEN" : "Fenny Stratford",
            "FER" : "Fernhill",
            "FRY" : "Ferriby",
            "FYS" : "Ferryside",
            "FFA" : "Ffairfach",
            "FIL" : "Filey",
            "FIT" : "Filton Abbey Wood",
            "" : "F",
            "FPK" : "Finsbury Park",
            "FIN" : "Finstock",
            "" : "F",
            "FSG" : "Fishersgate",
            "FGH" : "Fishguard Harbour",
            "FSK" : "Fiskerton",
            "FZW" : "Fitzwilliam",
            "FWY" : "Five Ways",
            "FLE" : "Fleet",
            "FLM" : "Flimby",
            "FLN" : "Flint",
            "FLT" : "Flitwick",
            "FLI" : "Flixton",
            "FLF" : "Flowery Field",
            "FKC" : "Folkestone Central",
            "FKW" : "Folkestone West",
            "FOD" : "Ford",
            "FOG" : "Forest Gate",
            "FOH" : "Forest Hill",
            "FBY" : "Formby",
            "FOR" : "Forres",
            "FRS" : "Forsinard",
            "FTM" : "Fort Matilda",
            "FTW" : "Fort William",
            "FOK" : "Four Oaks",
            "FOX" : "Foxfield",
            "FXN" : "Foxton",
            "FRT" : "Frant",
            "FTN" : "Fratton",
            "FRE" : "Freshfield",
            "FFD" : "Freshford",
            "FML" : "Frimley",
            "FRI" : "Frinton on Sea",
            "FZH" : "Frizinghall",
            "FRD" : "Frodsham",
            "FRO" : "Frome",
            "FLW" : "Fulwell",
            "FNV" : "Furness Vale",
            "FZP" : "Furze Platt",
            "GNB" : "Gainsborough Central",
            "GBL" : "Gainsborough Lea Road",
            "GCH" : "Garelochhead",
            "GRF" : "Garforth",
            "GGV" : "Gargrave",
            "GAR" : "Garrowhill",
            "GRS" : "Garscadden",
            "GSD" : "Garsdale",
            "" : "G",
            "GSW" : "Garswood",
            "GRH" : "Gartcosh",
            "" : "G",
            "" : "G",
            "GVE" : "Garve",
            "GST" : "Gathurst",
            "GTY" : "Gatley",
            "GTW" : "Gatwick Airport",
            "GGJ" : "Georgemas Junction",
            "GER" : "Gerrards Cross",
            "GDP" : "Gidea Park",
            "GFN" : "Giffnock",
            "GIG" : "Giggleswick",
            "GBD" : "Gilberdyke",
            "GFF" : "Gilfach Fargoed",
            "" : "G",
            "" : "G",
            "GSC" : "Gilshochill",
            "GIP" : "Gipsy Hill",
            "GIR" : "Girvan",
            "GLS" : "Glaisdale",
            "GCW" : "Glan Conwy",
            "GLC" : "Glasgow Central",
            "GLQ" : "Glasgow Queen Street",
            "GLH" : "Glasshoughton",
            "GLZ" : "Glazebrook",
            "GLE" : "Gleneagles",
            "GLF" : "Glenfinnan",
            "GLG" : "Glengarnock",
            "GLT" : "Glenrothes with Thornton",
            "GLO" : "Glossop",
            "GCR" : "Gloucester",
            "GLY" : "Glynde",
            "GOB" : "Gobowen",
            "GOD" : "Godalming",
            "GDL" : "Godley",
            "GDN" : "Godstone",
            "GOE" : "Goldthorpe",
            "GOF" : "Golf Street",
            "GOL" : "Golspie",
            "GOM" : "Gomshall",
            "GMY" : "Goodmayes",
            "GOO" : "Goole",
            "GTR" : "Goostrey",
            "GDH" : "Gordon Hill",
            "" : "G",
            "" : "G",
            "GTO" : "Gorton",
            "GPO" : "Gospel Oak",
            "GRK" : "Gourock",
            "GWN" : "Gowerton",
            "GOX" : "Goxhill",
            "GPK" : "Grange Park",
            "" : "G",
            "GTN" : "Grangetown",
            "GRA" : "Grantham",
            "GRT" : "Grateley",
            "GVH" : "Gravelly Hill",
            "GRV" : "Gravesend",
            "GRY" : "Grays",
            "GTA" : "Great Ayton",
            "GRB" : "Great Bentley",
            "GRC" : "Great Chesterford",
            "GCT" : "Great Coates",
            "GMV" : "Great Malvern",
            "GMN" : "Great Missenden",
            "GYM" : "Great Yarmouth",
            "GNL" : "Green Lane",
            "GNR" : "Green Road",
            "GBK" : "Greenbank",
            "GRL" : "Greenfaulds",
            "GNF" : "Greenfield",
            "GFD" : "Greenford",
            "GNH" : "Greenhithe for Bluewater",
            "GKC" : "Greenock Central",
            "GKW" : "Greenock West",
            "GNW" : "Greenwich",
            "GEA" : "Gretna Green",
            "GMD" : "Grimsby Docks",
            "GMB" : "Grimsby Town",
            "GRN" : "Grindleford",
            "GMT" : "Grosmont",
            "GRP" : "Grove Park",
            "GUI" : "Guide Bridge",
            "GLD" : "Guildford",
            "GSY" : "Guiseley",
            "GUN" : "Gunnersbury",
            "GSL" : "Gunnislake",
            "GNT" : "Gunton",
            "GWE" : "Gwersyllt",
            "GYP" : "Gypsy Lane",
            "HAB" : "Habrough",
            "HCB" : "Hackbridge",
            "HKC" : "Hackney Central",
            "HAC" : "Hackney Downs",
            "HKW" : "Hackney Wick",
            "" : "H",
            "HAD" : "Haddiscoe",
            "HDF" : "Hadfield",
            "HDW" : "Hadley Wood",
            "HGF" : "Hag Fold",
            "HAG" : "Hagley",
            "HMY" : "Hairmyres",
            "HAL" : "Hale",
            "HAS" : "Halesworth",
            "HED" : "Halewood",
            "HFX" : "Halifax",
            "HLG" : "Hall Green",
            "HID" : "Hall I Th Wood",
            "HLR" : "Hall Road",
            "HAI" : "Halling",
            "HWH" : "Haltwhistle",
            "HMT" : "Ham Street",
            "HME" : "Hamble",
            "HNC" : "Hamilton Central",
            "BKQ" : "Hamilton Square",
            "HNW" : "Hamilton West",
            "HMM" : "Hammerton",
            "HMD" : "Hampden Park",
            "HDH" : "Hampstead Heath",
            "HMP" : "Hampton",
            "HMC" : "Hampton Court",
            "HMW" : "Hampton Wick",
            "" : "H",
            "HSD" : "Hamstead",
            "HAM" : "Hamworthy",
            "HND" : "Hanborough",
            "HTH" : "Handforth",
            "HAN" : "Hanwell",
            "HPN" : "Hapton",
            "HRL" : "Harlech",
            "HDN" : "Harlesden",
            "HRD" : "Harling Road",
            "HLN" : "Harlington",
            "HWM" : "Harlow Mill",
            "HWN" : "Harlow Town",
            "HRO" : "Harold Wood",
            "HPD" : "Harpenden",
            "HRM" : "Harrietsham",
            "HGY" : "Harringay",
            "HRY" : "Harringay Green Lanes",
            "HRR" : "Harrington",
            "HGT" : "Harrogate",
            "" : "H",
            "" : "H",
            "HTF" : "Hartford",
            "HBY" : "Hartlebury",
            "HPL" : "Hartlepool",
            "HTW" : "Hartwood",
            "HPQ" : "Harwich International",
            "HWC" : "Harwich Town",
            "HSL" : "Haslemere",
            "HSK" : "Hassocks",
            "HGS" : "Hastings",
            "HTE" : "Hatch End",
            "HAT" : "Hatfield",
            "" : "H",
            "HAP" : "Hatfield Peverel",
            "HSG" : "Hathersage",
            "HTY" : "Hattersley",
            "HTN" : "Hatton",
            "HAV" : "Havant",
            "HVN" : "Havenhouse",
            "HVF" : "Haverfordwest",
            "HWD" : "Hawarden",
            "HWB" : "Hawarden Bridge",
            "HKH" : "Hawkhead",
            "HDB" : "Haydon Bridge",
            "HYR" : "Haydons Road",
            "" : "H",
            "" : "H",
            "HYL" : "Hayle",
            "HYM" : "Haymarket",
            "HHE" : "Haywards Heath",
            "HAZ" : "Hazel Grove",
            "HCN" : "Headcorn",
            "HDY" : "Headingley",
            "HDL" : "Headstone Lane",
            "HDG" : "Heald Green",
            "HLI" : "Healing",
            "HHL" : "Heath High Level",
            "HLL" : "Heath Low Level",
            "HXX" : "Heathrow Airport T123",
            "HAF" : "Heathrow Airport T4",
            "HWV" : "Heathrow Airport T5",
            "HTC" : "Heaton Chapel",
            "HBD" : "Hebden Bridge",
            "HEC" : "Heckington",
            "HDE" : "Hedge End",
            "HNF" : "Hednesford",
            "HEI" : "Heighington",
            "HLC" : "Helensburgh Central",
            "HLU" : "Helensburgh Upper",
            "HLD" : "Hellifield",
            "HMS" : "Helmsdale",
            "HSB" : "Helsby",
            "HML" : "Hemel Hempstead",
            "HEN" : "Hendon",
            "HNG" : "Hengoed",
            "" : "H",
            "" : "H",
            "HEL" : "Hensall",
            "HFD" : "Hereford",
            "HNB" : "Herne Bay",
            "HNH" : "Herne Hill",
            "HER" : "Hersham",
            "HFE" : "Hertford East",
            "HFN" : "Hertford North",
            "HES" : "Hessle",
            "HSW" : "Heswall",
            "HEV" : "Hever",
            "HEW" : "Heworth",
            "HEX" : "Hexham",
            "HYD" : "Heyford",
            "HHB" : "Heysham Port",
            "HIB" : "High Brooms",
            "" : "H",
            "ZHS" : "High Street Kensington Underground",
            "HWY" : "High Wycombe",
            "HGM" : "Higham",
            "HIP" : "Highams Park",
            "" : "H",
            "" : "H",
            "HTO" : "Hightown",
            "HLB" : "Hildenborough",
            "HLF" : "Hillfoot",
            "HLE" : "Hillington East",
            "HLW" : "Hillington West",
            "HIL" : "Hillside",
            "HLS" : "Hilsea",
            "HYW" : "Hinchley Wood",
            "HNK" : "Hinckley",
            "HIN" : "Hindley",
            "HNA" : "Hinton Admiral",
            "HIT" : "Hitchin",
            "HGR" : "Hither Green",
            "HOC" : "Hockley",
            "HBN" : "Hollingbourne",
            "HOD" : "Hollinwood",
            "HCH" : "Holmes Chapel",
            "HLM" : "Holmwood",
            "HOL" : "Holton Heath",
            "HHD" : "Holyhead",
            "HLY" : "Holytown",
            "HMN" : "Homerton",
            "HYB" : "Honeybourne",
            "HON" : "Honiton",
            "HOY" : "Honley",
            "HPA" : "Honor Oak Park",
            "HOK" : "Hook",
            "HOO" : "Hooton",
            "" : "H",
            "" : "H",
            "HPT" : "Hopton Heath",
            "HOR" : "Horley",
            "HBP" : "Hornbeam Park",
            "HRN" : "Hornsey",
            "HRS" : "Horsforth",
            "HRH" : "Horsham",
            "HSY" : "Horsley",
            "" : "H",
            "HWI" : "Horwich Parkway",
            "HSC" : "Hoscar",
            "HGN" : "Hough Green",
            "HOU" : "Hounslow",
            "HOV" : "Hove",
            "" : "H",
            "HWW" : "How Wood",
            "HOW" : "Howden",
            "" : "H",
            "HYK" : "Hoylake",
            "HBB" : "Hubberts Bridge",
            "HKN" : "Hucknall",
            "HUD" : "Huddersfield",
            "HUL" : "Hull Paragon",
            "HUP" : "Humphrey Park",
            "HCT" : "Huncoat",
            "HGD" : "Hungerford",
            "HUB" : "Hunmanby",
            "HUN" : "Huntingdon",
            "HNT" : "Huntly",
            "HNX" : "Hunts Cross",
            "HUR" : "Hurst Green",
            "HUT" : "Hutton Cranswick",
            "HUY" : "Huyton",
            "HYC" : "Hyde Central",
            "HYT" : "Hyde North",
            "HKM" : "Hykeham",
            "HYN" : "Hyndland",
            "HYH" : "Hythe",
            "IBM" : "IBM",
            "IFI" : "Ifield",
            "IFD" : "Ilford",
            "ILK" : "Ilkley",
            "IMW" : "Imperial Wharf",
            "INC" : "Ince",
            "" : "I",
            "INT" : "Ingatestone",
            "INS" : "Insch",
            "IGD" : "Invergordon",
            "ING" : "Invergowrie",
            "INK" : "Inverkeithing",
            "INP" : "Inverkip",
            "INV" : "Inverness",
            "INH" : "Invershin",
            "INR" : "Inverurie",
            "IPS" : "Ipswich",
            "IRL" : "Irlam",
            "IRV" : "Irvine",
            "ISL" : "Isleworth",
            "ISP" : "Islip",
            "IVR" : "Iver",
            "IVY" : "Ivybridge",
            "JEQ" : "Jewellery Quarter",
            "JOH" : "Johnston",
            "JHN" : "Johnstone",
            "JOR" : "Jordanhill",
            "KSL" : "Kearsley",
            "KSN" : "Kearsney",
            "KEI" : "Keighley",
            "KEH" : "Keith",
            "KEL" : "Kelvedon",
            "KVD" : "Kelvindale",
            "KEM" : "Kemble",
            "KMH" : "Kempston Hardwick",
            "KMP" : "Kempton Park",
            "KMS" : "Kemsing",
            "KML" : "Kemsley",
            "KEN" : "Kendal",
            "KLY" : "Kenley",
            "KNE" : "Kennett",
            "KNS" : "Kennishead",
            "KNL" : "Kensal Green",
            "KNR" : "Kensal Rise",
            "KPA" : "Kensington Olympia",
            "KTH" : "Kent House",
            "KTN" : "Kentish Town",
            "KTW" : "Kentish Town West",
            "KNT" : "Kenton",
            "KBK" : "Kents Bank",
            "KET" : "Kettering",
            "KWB" : "Kew Bridge",
            "KWG" : "Kew Gardens",
            "KEY" : "Keyham",
            "KYN" : "Keynsham",
            "KDB" : "Kidbrooke",
            "KID" : "Kidderminster",
            "KDG" : "Kidsgrove",
            "KWL" : "Kidwelly",
            "KBN" : "Kilburn High Road",
            "KLD" : "Kildale",
            "KIL" : "Kildonan",
            "KGT" : "Kilgetty",
            "KMK" : "Kilmarnock",
            "KLM" : "Kilmaurs",
            "KPT" : "Kilpatrick",
            "KWN" : "Kilwinning",
            "KBC" : "Kinbrace",
            "KGM" : "Kingham",
            "KGH" : "Kinghorn",
            "KGL" : "Kings Langley",
            "" : "K",
            "KNN" : "Kings Norton",
            "KGN" : "Kings Nympton",
            "KGP" : "Kings Park",
            "KGS" : "Kings Sutton",
            "KGE" : "Kingsknowe",
            "KNG" : "Kingston",
            "KND" : "Kingswood",
            "KIN" : "Kingussie",
            "KIT" : "Kintbury",
            "KBX" : "Kirby Cross",
            "KKS" : "Kirk Sandall",
            "KIR" : "Kirkby",
            "KKB" : "Kirkby in Ashfield",
            "KSW" : "Kirkby Stephen",
            "" : "K",
            "KDY" : "Kirkcaldy",
            "KRK" : "Kirkconnel",
            "KKD" : "Kirkdale",
            "" : "K",
            "KKH" : "Kirkhill",
            "KKN" : "Kirknewton",
            "KWD" : "Kirkwood",
            "KTL" : "Kirton Lindsey",
            "KIV" : "Kiveton Bridge",
            "KVP" : "Kiveton Park",
            "KNA" : "Knaresborough",
            "KBW" : "Knebworth",
            "KNI" : "Knighton",
            "KCK" : "Knockholt",
            "KNO" : "Knottingley",
            "KNU" : "Knucklas",
            "KNF" : "Knutsford",
            "KYL" : "Kyle of Lochalsh",
            "LDY" : "Ladybank",
            "LAD" : "Ladywell",
            "LAI" : "Laindon",
            "LRG" : "Lairg",
            "LKE" : "Lake",
            "LAK" : "Lakenheath",
            "LAM" : "Lamphey",
            "LNK" : "Lanark",
            "LAN" : "Lancaster",
            "LAC" : "Lancing",
            "LAW" : "Landywood",
            "LGB" : "Langbank",
            "LHO" : "Langho",
            "LNY" : "Langley",
            "LGG" : "Langley Green",
            "LGM" : "Langley Mill",
            "LGS" : "Langside",
            "LGW" : "Langwathby",
            "" : "L",
            "LAP" : "Lapford",
            "LPW" : "Lapworth",
            "LBT" : "Larbert",
            "LAR" : "Largs",
            "LRH" : "Larkhall",
            "LAU" : "Laurencekirk",
            "LWH" : "Lawrence Hill",
            "LAY" : "Layton",
            "" : "L",
            "LEG" : "Lea Green",
            "LEH" : "Lea Hall",
            "LEA" : "Leagrave",
            "LHM" : "Lealholm",
            "LMS" : "Leamington Spa",
            "LSW" : "Leasowe",
            "LHD" : "Leatherhead",
            "LED" : "Ledbury",
            "LEE" : "Lee",
            "LDS" : "Leeds",
            "LEI" : "Leicester",
            "" : "L",
            "" : "L",
            "LBZ" : "Leighton Buzzard",
            "LEL" : "Lelant",
            "LTS" : "Lelant Saltings",
            "LEN" : "Lenham",
            "LNZ" : "Lenzie",
            "LEO" : "Leominster",
            "LET" : "Letchworth Garden City",
            "" : "L",
            "LVM" : "Levenshulme",
            "LWS" : "Lewes",
            "LEW" : "Lewisham",
            "LEY" : "Leyland",
            "LEM" : "Leyton Midland Road",
            "LER" : "Leytonstone High Road",
            "LIC" : "Lichfield City",
            "LTV" : "Lichfield Trent Valley",
            "LID" : "Lidlington",
            "LHS" : "Limehouse",
            "LCN" : "Lincoln Central",
            "LFD" : "Lingfield",
            "LGD" : "Lingwood",
            "LIN" : "Linlithgow",
            "LIP" : "Liphook",
            "LSK" : "Liskeard",
            "LIS" : "Liss",
            "" : "L",
            "LTK" : "Little Kimble",
            "LTT" : "Little Sutton",
            "LTL" : "Littleborough",
            "LIT" : "Littlehampton",
            "LVN" : "Littlehaven",
            "LTP" : "Littleport",
            "LVC" : "Liverpool Central",
            "LVJ" : "Liverpool James Street",
            "LIV" : "Liverpool Lime Street",
            "LPY" : "Liverpool South Parkway",
            "LSN" : "Livingston North",
            "LVG" : "Livingston South",
            "LLA" : "Llanaber",
            "LBR" : "Llanbedr",
            "LLT" : "Llanbister Road",
            "LNB" : "Llanbradach",
            "LLN" : "Llandaf",
            "LDN" : "Llandanwg",
            "LLC" : "Llandecwyn",
            "LLL" : "Llandeilo",
            "LLV" : "Llandovery",
            "LLO" : "Llandrindod",
            "LLD" : "Llandudno",
            "LLJ" : "Llandudno Junction",
            "LLI" : "Llandybie",
            "LLE" : "Llanelli",
            "LLF" : "Llanfairfechan",
            "LPG" : "Llanfairpwll",
            "LLG" : "Llangadog",
            "LLM" : "Llangammarch",
            "LLH" : "Llangennech",
            "LGO" : "Llangynllo",
            "LLR" : "Llanharan",
            "LTH" : "Llanhilleth",
            "LLS" : "Llanishen",
            "LWR" : "Llanrwst",
            "LAS" : "Llansamlet",
            "LWM" : "Llantwit Major",
            "LNR" : "Llanwrda",
            "LNW" : "Llanwrtyd",
            "LLW" : "Llwyngwril",
            "LLY" : "Llwynypia",
            "LHA" : "Loch Awe",
            "LHE" : "Loch Eil Outward Bound",
            "LCL" : "Lochailort",
            "LCS" : "Locheilside",
            "LCG" : "Lochgelly",
            "LCC" : "Lochluichart",
            "LHW" : "Lochwinnoch",
            "LOC" : "Lockerbie",
            "LCK" : "Lockwood",
            "BFR" : "London Blackfriars",
            "LBG" : "London Bridge",
            "CST" : "London Cannon Street",
            "CHX" : "London Charing Cross",
            "EUS" : "London Euston",
            "FST" : "London Fenchurch Street",
            "LOF" : "London Fields",
            "KGX" : "London Kings Cross",
            "LST" : "London Liverpool Street",
            "MYB" : "London Marylebone",
            "PAD" : "London Paddington",
            "" : "L",
            "" : "L",
            "STP" : "London St Pancras Domestic",
            "" : "L",
            "VIC" : "London Victoria",
            "WAT" : "London Waterloo",
            "WAE" : "London Waterloo East",
            "LBK" : "Long Buckby",
            "LGE" : "Long Eaton",
            "LPR" : "Long Preston",
            "LGK" : "Longbeck",
            "LOB" : "Longbridge",
            "LNG" : "Longcross",
            "LGF" : "Longfield",
            "LND" : "Longniddry",
            "LPT" : "Longport",
            "LGN" : "Longton",
            "LOO" : "Looe",
            "LOT" : "Lostock",
            "LTG" : "Lostock Gralam",
            "LOH" : "Lostock Hall",
            "LOS" : "Lostwithiel",
            "LBO" : "Loughborough",
            "LGJ" : "Loughborough Junction",
            "LOW" : "Lowdham",
            "LSY" : "Lower Sydenham",
            "LWT" : "Lowestoft",
            "LUD" : "Ludlow",
            "LUT" : "Luton",
            "LTN" : "Luton Airport Parkway",
            "LUX" : "Luxulyan",
            "LYD" : "Lydney",
            "LYE" : "Lye",
            "LYP" : "Lymington Pier",
            "LYT" : "Lymington Town",
            "LYC" : "Lympstone Commando",
            "LYM" : "Lympstone Village",
            "LTM" : "Lytham",
            "MAC" : "Macclesfield",
            "MCN" : "Machynlleth",
            "MST" : "Maesteg",
            "" : "M",
            "MAG" : "Maghull",
            "MDN" : "Maiden Newton",
            "MAI" : "Maidenhead",
            "MDB" : "Maidstone Barracks",
            "MDE" : "Maidstone East",
            "MDW" : "Maidstone West",
            "MAL" : "Malden Manor",
            "MLG" : "Mallaig",
            "MLT" : "Malton",
            "MVL" : "Malvern Link",
            "MIA" : "Manchester Airport",
            "MCO" : "Manchester Oxford Road",
            "MAN" : "Manchester Piccadilly",
            "MUF" : "Manchester United FC Halt",
            "MCV" : "Manchester Victoria",
            "MNE" : "Manea",
            "MNG" : "Manningtree",
            "MNP" : "Manor Park",
            "MNR" : "Manor Road",
            "MRB" : "Manorbier",
            "MAS" : "Manors",
            "MFT" : "Mansfield",
            "MSW" : "Mansfield Woodhouse",
            "MCH" : "March",
            "MRN" : "Marden",
            "MAR" : "Margate",
            "MHR" : "Market Harborough",
            "MKR" : "Market Rasen",
            "MNC" : "Markinch",
            "MKT" : "Marks Tey",
            "MLW" : "Marlow",
            "MPL" : "Marple",
            "MSN" : "Marsden",
            "MSK" : "Marske",
            "MGN" : "Marston Green",
            "MTM" : "Martin Mill",
            "MAO" : "Martins Heron",
            "MTO" : "Marton",
            "MYH" : "Maryhill",
            "MYL" : "Maryland",
            "MRY" : "Maryport",
            "MAT" : "Matlock",
            "MTB" : "Matlock Bath",
            "MAU" : "Mauldeth Road",
            "MAX" : "Maxwell Park",
            "MAY" : "Maybole",
            "MZH" : "Maze Hill",
            "MHS" : "Meadowhall",
            "MEL" : "Meldreth",
            "MKM" : "Melksham",
            "MES" : "Melton",
            "MMO" : "Melton Mowbray",
            "MEN" : "Menheniot",
            "MNN" : "Menston",
            "MEO" : "Meols",
            "MEC" : "Meols Cop",
            "MEP" : "Meopham",
            "MEY" : "Merrytown",
            "MHM" : "Merstham",
            "MER" : "Merthyr Tydfil",
            "MEV" : "Merthyr Vale",
            "MGM" : "Metheringham",
            "MCE" : "MetroCentre",
            "MEX" : "Mexborough",
            "MIC" : "Micheldever",
            "MIK" : "Micklefield",
            "MBR" : "Middlesbrough",
            "MDL" : "Middlewood",
            "MDG" : "Midgham",
            "MFH" : "Milford Haven",
            "" : "M",
            "MIL" : "Mill Hill Broadway",
            "" : "M",
            "" : "M",
            "" : "M",
            "MIN" : "Milliken Park",
            "MLM" : "Millom",
            "MIH" : "Mills Hill",
            "MLN" : "Milngavie",
            "MLR" : "Milnrow",
            "MKC" : "Milton Keynes Central",
            "MFF" : "Minffordd",
            "MSR" : "Minster",
            "MIR" : "Mirfield",
            "MIS" : "Mistley",
            "MTC" : "Mitcham Eastfields",
            "MIJ" : "Mitcham Junction",
            "MOB" : "Mobberley",
            "MON" : "Monifieth",
            "MRS" : "Monks Risborough",
            "MTP" : "Montpelier",
            "MTS" : "Montrose",
            "MRF" : "Moorfields",
            "MOG" : "Moorgate",
            "MSD" : "Moorside",
            "MRP" : "Moorthorpe",
            "MRR" : "Morar",
            "MRD" : "Morchard Road",
            "MDS" : "Morden South",
            "MCM" : "Morecambe",
            "" : "M",
            "" : "M",
            "" : "M",
            "MFA" : "Morfa Mawddach",
            "MLY" : "Morley",
            "MPT" : "Morpeth",
            "MOR" : "Mortimer",
            "MTL" : "Mortlake",
            "MSS" : "Moses Gate",
            "MOS" : "Moss Side",
            "MSL" : "Mossley",
            "MSH" : "Mossley Hill",
            "MPK" : "Mosspark",
            "MSO" : "Moston",
            "MTH" : "Motherwell",
            "MOT" : "Motspur Park",
            "MTG" : "Mottingham",
            "" : "M",
            "MLD" : "Mouldsworth",
            "MCB" : "Moulsecoomb",
            "MFL" : "Mount Florida",
            "MTV" : "Mount Vernon",
            "MTA" : "Mountain Ash",
            "MOO" : "Muir of Ord",
            "MUI" : "Muirend",
            "MUB" : "Musselburgh",
            "MYT" : "Mytholmroyd",
            "NFN" : "Nafferton",
            "" : "N",
            "NRN" : "Nairn",
            "NAN" : "Nantwich",
            "NAR" : "Narberth",
            "NBR" : "Narborough",
            "NVR" : "Navigation Road",
            "NTH" : "Neath",
            "NMT" : "Needham Market",
            "NEI" : "Neilston",
            "NEL" : "Nelson",
            "NES" : "Neston",
            "NET" : "Netherfield",
            "NRT" : "Nethertown",
            "NTL" : "Netley",
            "NBA" : "New Barnet",
            "NBC" : "New Beckenham",
            "NBN" : "New Brighton",
            "NCE" : "New Clee",
            "NWX" : "New Cross",
            "NXG" : "New Cross Gate",
            "NCK" : "New Cumnock",
            "NEH" : "New Eltham",
            "NHY" : "New Hey",
            "NHL" : "New Holland",
            "NHE" : "New Hythe",
            "NLN" : "New Lane",
            "NEM" : "New Malden",
            "NMC" : "New Mills Central",
            "NMN" : "New Mills Newtown",
            "NWM" : "New Milton",
            "NPD" : "New Pudsey",
            "NSG" : "New Southgate",
            "NCT" : "Newark Castle",
            "NNG" : "Newark North Gate",
            "NBE" : "Newbridge",
            "NBY" : "Newbury",
            "NRC" : "Newbury Racecourse",
            "NCL" : "Newcastle",
            "NEW" : "Newcraighall",
            "NVH" : "Newhaven Harbour",
            "NVN" : "Newhaven Town",
            "NGT" : "Newington",
            "NMK" : "Newmarket",
            "" : "N",
            "" : "N",
            "NQY" : "Newquay",
            "NSD" : "Newstead",
            "NTA" : "Newton Abbot",
            "NAY" : "Newton Aycliffe",
            "NWN" : "Newton for Hyde",
            "" : "N",
            "NTC" : "Newton St Cyres",
            "" : "N",
            "NWR" : "Newtonmore",
            "" : "N",
            "" : "N",
            "NNP" : "Ninian Park",
            "NIT" : "Nitshill",
            "NBT" : "Norbiton",
            "NRB" : "Norbury",
            "NSB" : "Normans Bay",
            "NOR" : "Normanton",
            "NBW" : "North Berwick",
            "NCM" : "North Camp",
            "NDL" : "North Dulwich",
            "NFA" : "North Fambridge",
            "NLR" : "North Llanrwst",
            "NQU" : "North Queensferry",
            "NRD" : "North Road",
            "NSH" : "North Sheen",
            "NWA" : "North Walsham",
            "NWB" : "North Wembley",
            "NTR" : "Northallerton",
            "NMP" : "Northampton",
            "NFD" : "Northfield",
            "NFL" : "Northfleet",
            "NLT" : "Northolt Park",
            "NUM" : "Northumberland Park",
            "NWI" : "Northwich",
            "NTB" : "Norton Bridge",
            "NRW" : "Norwich",
            "NWD" : "Norwood Junction",
            "NOT" : "Nottingham",
            "NUN" : "Nuneaton",
            "NHD" : "Nunhead",
            "NNT" : "Nunthorpe",
            "NUT" : "Nutbourne",
            "NUF" : "Nutfield",
            "OKN" : "Oakengates",
            "OKM" : "Oakham",
            "OKL" : "Oakleigh Park",
            "OBN" : "Oban",
            "OCK" : "Ockendon",
            "OLY" : "Ockley",
            "OKE" : "Okehampton",
            "OHL" : "Old Hill",
            "ORN" : "Old Roan",
            "OLD" : "Old Street",
            "OLF" : "Oldfield Park",
            "OLM" : "Oldham Mumps",
            "OLW" : "Oldham Werneth",
            "OLT" : "Olton",
            "ORE" : "Ore",
            "OMS" : "Ormskirk",
            "ORP" : "Orpington",
            "ORR" : "Orrell",
            "OPK" : "Orrell Park",
            "OTF" : "Otford",
            "OUN" : "Oulton Broad North",
            "OUS" : "Oulton Broad South",
            "OUT" : "Outwood",
            "OVE" : "Overpool",
            "OVR" : "Overton",
            "OXN" : "Oxenholme Lake District",
            "OXF" : "Oxford",
            "OXS" : "Oxshott",
            "OXT" : "Oxted",
            "PDW" : "Paddock Wood",
            "PDG" : "Padgate",
            "PGN" : "Paignton",
            "PCN" : "Paisley Canal",
            "PYG" : "Paisley Gilmour Street",
            "PYJ" : "Paisley St James",
            "PAL" : "Palmers Green",
            "PAN" : "Pangbourne",
            "PNL" : "Pannal",
            "PTF" : "Pantyffynnon",
            "PAR" : "Par",
            "PBL" : "Parbold",
            "PKT" : "Park Street",
            "" : "P",
            "PSN" : "Parson Street",
            "PTK" : "Partick",
            "PRN" : "Parton",
            "PWY" : "Patchway",
            "PAT" : "Patricroft",
            "PTT" : "Patterton",
            "PEA" : "Peartree",
            "PMR" : "Peckham Rye",
            "PEG" : "Pegswood",
            "PEM" : "Pemberton",
            "" : "P",
            "PMB" : "Pembroke",
            "PMD" : "Pembroke Dock",
            "PNA" : "Penally",
            "PEN" : "Penarth",
            "PCD" : "Pencoed",
            "PGM" : "Pengam",
            "PNE" : "Penge East",
            "PNW" : "Penge West",
            "PHG" : "Penhelig",
            "PNS" : "Penistone",
            "PKG" : "Penkridge",
            "PMW" : "Penmaenmawr",
            "PNM" : "Penmere",
            "PER" : "Penrhiwceiber",
            "PRH" : "Penrhyndeudraeth",
            "PNR" : "Penrith",
            "PYN" : "Penryn",
            "" : "P",
            "PHR" : "Penshurst",
            "" : "P",
            "" : "P",
            "BPC" : "Penychain",
            "PNF" : "Penyffordd",
            "PNZ" : "Penzance",
            "PRW" : "Perranwell",
            "PRY" : "Perry Barr",
            "PSH" : "Pershore",
            "PTH" : "Perth",
            "PBO" : "Peterborough",
            "PTR" : "Petersfield",
            "PET" : "Petts Wood",
            "" : "P",
            "PEB" : "Pevensey Bay",
            "PEW" : "Pewsey",
            "PIL" : "Pilning",
            "PIN" : "Pinhoe",
            "PIT" : "Pitlochry",
            "PSE" : "Pitsea",
            "PLS" : "Pleasington",
            "PLK" : "Plockton",
            "PLC" : "Pluckley",
            "PLM" : "Plumley",
            "PMP" : "Plumpton",
            "PLU" : "Plumstead",
            "PLY" : "Plymouth",
            "POK" : "Pokesdown",
            "PLG" : "Polegate",
            "PSW" : "Polesworth",
            "PWE" : "Pollokshaws East",
            "PWW" : "Pollokshaws West",
            "PLE" : "Pollokshields East",
            "PLW" : "Pollokshields West",
            "PMT" : "Polmont",
            "POL" : "Polsloe Bridge",
            "PON" : "Ponders End",
            "PTD" : "Pontarddulais",
            "PFR" : "Pontefract Baghill",
            "PFM" : "Pontefract Monkhill",
            "POT" : "Pontefract Tanshelf",
            "PLT" : "Pontlottyn",
            "PYC" : "Pontyclun",
            "" : "P",
            "" : "P",
            "PPD" : "Pontypridd",
            "POO" : "Poole",
            "POP" : "Poppleton",
            "PTG" : "Port Glasgow",
            "PSL" : "Port Sunlight",
            "PTA" : "Port Talbot Parkway",
            "PTC" : "Portchester",
            "POR" : "Porth",
            "PTM" : "Porthmadog",
            "PLN" : "Portlethen",
            "PLD" : "Portslade",
            "" : "P",
            "PMA" : "Portsmouth Arms",
            "PMH" : "Portsmouth Harbour",
            "" : "P",
            "PBR" : "Potters Bar",
            "" : "P",
            "PYT" : "Poynton",
            "PRS" : "Prees",
            "PSC" : "Prescot",
            "PRT" : "Prestatyn",
            "PRB" : "Prestbury",
            "PRE" : "Preston",
            "PRP" : "Preston Park",
            "PST" : "Prestonpans",
            "PRA" : "Prestwick International Airport",
            "PTW" : "Prestwick Town",
            "" : "P",
            "PRR" : "Princes Risborough",
            "PRL" : "Prittlewell",
            "PRU" : "Prudhoe",
            "PUL" : "Pulborough",
            "PFL" : "Purfleet",
            "PUR" : "Purley",
            "PUO" : "Purley Oaks",
            "PUT" : "Putney",
            "PWL" : "Pwllheli",
            "PYL" : "Pyle",
            "QYD" : "Quakers Yard",
            "QBR" : "Queenborough",
            "" : "Q",
            "" : "Q",
            "" : "Q",
            "" : "Q",
            "QUI" : "Quintrel Downs",
            "" : "Q",
            "RDT" : "Radlett",
            "RAD" : "Radley",
            "RDR" : "Radyr",
            "RNF" : "Rainford",
            "" : "R",
            "" : "R",
            "RNH" : "Rainhill",
            "RAM" : "Ramsgate",
            "" : "R",
            "RAN" : "Rannoch",
            "RAU" : "Rauceby",
            "RAV" : "Ravenglass for Eskdale",
            "RVB" : "Ravensbourne",
            "RVN" : "Ravensthorpe",
            "RWC" : "Rawcliffe",
            "RLG" : "Rayleigh",
            "RAY" : "Raynes Park",
            "RDG" : "Reading",
            "RDW" : "Reading West",
            "REC" : "Rectory Road",
            "RDB" : "Redbridge",
            "RCC" : "Redcar Central",
            "RCE" : "Redcar East",
            "RDN" : "Reddish North",
            "RDS" : "Reddish South",
            "RDC" : "Redditch",
            "RDH" : "Redhill",
            "RDA" : "Redland",
            "RED" : "Redruth",
            "" : "R",
            "" : "R",
            "REI" : "Reigate",
            "RTN" : "Renton",
            "RET" : "Retford",
            "RHI" : "Rhiwbina",
            "RIA" : "Rhoose Cardiff International Airport",
            "RHO" : "Rhosneigr",
            "RHL" : "Rhyl",
            "RHY" : "Rhymney",
            "RHD" : "Ribblehead",
            "RIL" : "Rice Lane",
            "RMD" : "Richmond",
            "RIC" : "Rickmansworth",
            "RDD" : "Riddlesdown",
            "RID" : "Ridgmont",
            "RDM" : "Riding Mill",
            "" : "R",
            "RIS" : "Rishton",
            "RBR" : "Robertsbridge",
            "ROB" : "Roby",
            "RCD" : "Rochdale",
            "ROC" : "Roche",
            "RTR" : "Rochester",
            "RFD" : "Rochford",
            "RFY" : "Rock Ferry",
            "ROG" : "Rogart",
            "ROR" : "Rogerstone",
            "ROL" : "Rolleston",
            "RMB" : "Roman Bridge",
            "RMF" : "Romford",
            "RML" : "Romiley",
            "ROM" : "Romsey",
            "ROO" : "Roose",
            "RSG" : "Rose Grove",
            "RSH" : "Rose Hill Marple",
            "ROS" : "Rosyth",
            "RMC" : "Rotherham Central",
            "RNR" : "Roughton Road",
            "RLN" : "Rowlands Castle",
            "ROW" : "Rowley Regis",
            "RYB" : "Roy Bridge",
            "RYN" : "Roydon",
            "RYS" : "Royston",
            "RUA" : "Ruabon",
            "RUF" : "Rufford",
            "RUG" : "Rugby",
            "RGT" : "Rugeley Town",
            "RGL" : "Rugeley Trent Valley",
            "RUN" : "Runcorn",
            "RUE" : "Runcorn East",
            "RKT" : "Ruskington",
            "RUS" : "Ruswarp",
            "RUT" : "Rutherglen",
            "RYR" : "Ryde St Johns Road",
            "RYD" : "Ryde Esplanade",
            "RYP" : "Ryde Pier Head",
            "RRB" : "Ryder Brow",
            "RYE" : "Rye",
            "RYH" : "Rye House",
            "SFD" : "Salford Central",
            "SLD" : "Salford Crescent",
            "SAF" : "Salfords",
            "SAH" : "Salhouse",
            "SAL" : "Salisbury",
            "SAE" : "Saltaire",
            "STS" : "Saltash",
            "SLB" : "Saltburn",
            "SLT" : "Saltcoats",
            "SAM" : "Saltmarshe",
            "SLW" : "Salwick",
            "SMC" : "Sampford Courtenay",
            "" : "S",
            "SDB" : "Sandbach",
            "SNR" : "Sanderstead",
            "SDL" : "Sandhills",
            "SND" : "Sandhurst",
            "SDG" : "Sandling",
            "SAN" : "Sandown",
            "SDP" : "Sandplace",
            "" : "S",
            "SDW" : "Sandwich",
            "SDY" : "Sandy",
            "SNK" : "Sankey for Penketh",
            "SQH" : "Sanquhar",
            "SRR" : "Sarn",
            "SDF" : "Saundersfoot",
            "SDR" : "Saunderton",
            "SAW" : "Sawbridgeworth",
            "SXY" : "Saxilby",
            "SAX" : "Saxmundham",
            "SCA" : "Scarborough",
            "SCT" : "Scotscalder",
            "SCH" : "Scotstounhill",
            "SCU" : "Scunthorpe",
            "SML" : "Sea Mills",
            "SEF" : "Seaford",
            "" : "S",
            "SEA" : "Seaham",
            "SEM" : "Seamer",
            "SSC" : "Seascale",
            "SEC" : "Seaton Carew",
            "" : "S",
            "SBY" : "Selby",
            "SRS" : "Selhurst",
            "SEL" : "Sellafield",
            "SEG" : "Selling",
            "SLY" : "Selly Oak",
            "SET" : "Settle",
            "SVK" : "Seven Kings",
            "SVS" : "Seven Sisters",
            "SEV" : "Sevenoaks",
            "SVB" : "Severn Beach",
            "STJ" : "Severn Tunnel Junction",
            "SFR" : "Shalford",
            "SHN" : "Shanklin",
            "" : "S",
            "SHW" : "Shawford",
            "SHL" : "Shawlands",
            "" : "S",
            "SHF" : "Sheffield",
            "SED" : "Shelford",
            "SNF" : "Shenfield",
            "SEN" : "Shenstone",
            "" : "S",
            "SPH" : "Shepherds Well",
            "SPY" : "Shepley",
            "SHP" : "Shepperton",
            "STH" : "Shepreth",
            "SHE" : "Sherborne",
            "" : "S",
            "SHM" : "Sheringham",
            "SLS" : "Shettleston",
            "SDM" : "Shieldmuir",
            "SFN" : "Shifnal",
            "SHD" : "Shildon",
            "SHI" : "Shiplake",
            "SHY" : "Shipley",
            "SPP" : "Shippea Hill",
            "SIP" : "Shipton",
            "SHB" : "Shirebrook",
            "SHH" : "Shirehampton",
            "SRO" : "Shireoaks",
            "SRL" : "Shirley",
            "SRY" : "Shoeburyness",
            "SHO" : "Sholing",
            "" : "S",
            "" : "S",
            "SRT" : "Shortlands",
            "SHT" : "Shotton",
            "SHS" : "Shotts",
            "SHR" : "Shrewsbury",
            "SID" : "Sidcup",
            "SIL" : "Sileby",
            "SIC" : "Silecroft",
            "SLK" : "Silkstone Common",
            "SLV" : "Silver Street",
            "SVR" : "Silverdale",
            "SIN" : "Singer",
            "SIT" : "Sittingbourne",
            "SKG" : "Skegness",
            "SKE" : "Skewen",
            "SKI" : "Skipton",
            "SGR" : "Slade Green",
            "SWT" : "Slaithwaite",
            "SLA" : "Slateford",
            "SLR" : "Sleaford",
            "SLH" : "Sleights",
            "SLO" : "Slough",
            "SMA" : "Small Heath",
            "SAB" : "Smallbrook Junction",
            "SGB" : "Smethwick Galton Bridge",
            "SMR" : "Smethwick Rolfe Street",
            "SMI" : "Smitham",
            "SMB" : "Smithy Bridge",
            "SNI" : "Snaith",
            "SDA" : "Snodland",
            "SWO" : "Snowdown",
            "SOR" : "Sole Street",
            "SOL" : "Solihull",
            "SYT" : "Somerleyton",
            "SAT" : "South Acton",
            "SBK" : "South Bank",
            "SBM" : "South Bermondsey",
            "SCY" : "South Croydon",
            "SES" : "South Elmsall",
            "SGN" : "South Greenford",
            "SGL" : "South Gyle",
            "SOH" : "South Hampstead",
            "SOK" : "South Kenton",
            "SMO" : "South Merton",
            "SOM" : "South Milford",
            "SRU" : "South Ruislip",
            "STO" : "South Tottenham",
            "SWS" : "South Wigston",
            "SOF" : "South Woodham Ferrers",
            "STL" : "Southall",
            "SOA" : "Southampton Airpt Parkway",
            "SOU" : "Southampton Central",
            "SOB" : "Southbourne",
            "SBU" : "Southbury",
            "SEE" : "Southease",
            "SOC" : "Southend Central",
            "SOE" : "Southend East",
            "SOV" : "Southend Victoria",
            "SMN" : "Southminster",
            "SOP" : "Southport",
            "SWK" : "Southwick",
            "SOW" : "Sowerby Bridge",
            "SPA" : "Spalding",
            "SBR" : "Spean Bridge",
            "SPI" : "Spital",
            "SPO" : "Spondon",
            "SPN" : "Spooner Row",
            "SRI" : "Spring Road",
            "SPR" : "Springburn",
            "SPF" : "Springfield",
            "SQU" : "Squires Gate",
            "SAC" : "St Albans",
            "SAA" : "St Albans Abbey",
            "SAR" : "St Andrews Road",
            "" : "S",
            "SAU" : "St Austell",
            "SBS" : "St Bees",
            "SBF" : "St Budeaux Ferry Road",
            "SBV" : "St Budeaux Victoria Road",
            "SCR" : "St Columb Road",
            "SDN" : "St Denys",
            "SER" : "St Erth",
            "SGM" : "St Germans",
            "SNH" : "St Helens Central",
            "SHJ" : "St Helens Junction",
            "SIH" : "St Helier",
            "" : "S",
            "SJP" : "St James Park",
            "SJS" : "St James Street",
            "SAJ" : "St Johns",
            "SKN" : "St Keyne Wishing Well Halt",
            "SLQ" : "St Leonards Warrior Square",
            "" : "S",
            "" : "S",
            "SMY" : "St Mary Cray",
            "STM" : "St Michaels",
            "SNO" : "St Neots",
            "STA" : "Stafford",
            "SNS" : "Staines",
            "SLL" : "Stallingborough",
            "SYB" : "Stalybridge",
            "SMD" : "Stamford",
            "SMH" : "Stamford Hill",
            "" : "S",
            "" : "S",
            "SSD" : "Stansted Airport",
            "SST" : "Stansted Mountfitchet",
            "SPU" : "Staplehurst",
            "SRD" : "Stapleton Road",
            "SBE" : "Starbeck",
            "SCS" : "Starcross",
            "" : "S",
            "SCF" : "Stechford",
            "" : "S",
            "SPS" : "Stepps",
            "SVG" : "Stevenage",
            "STV" : "Stevenston",
            "SWR" : "Stewartby",
            "STT" : "Stewarton",
            "STG" : "Stirling",
            "SPT" : "Stockport",
            "SKS" : "Stocksfield",
            "SSM" : "Stocksmoor",
            "STK" : "Stockton",
            "SKM" : "Stoke Mandeville",
            "SKW" : "Stoke Newington",
            "" : "S",
            "SNE" : "Stone",
            "SCG" : "Stone Crossing",
            "SBP" : "Stonebridge Park",
            "SOG" : "Stonegate",
            "STN" : "Stonehaven",
            "SHU" : "Stonehouse",
            "SNL" : "Stoneleigh",
            "SBJ" : "Stourbridge Junction",
            "SBT" : "Stourbridge Town",
            "SMK" : "Stowmarket",
            "STR" : "Stranraer",
            "" : "S",
            "" : "S",
            "STC" : "Strathcarron",
            "STW" : "Strawberry Hill",
            "STE" : "Streatham",
            "SRC" : "Streatham Common",
            "SRH" : "Streatham Hill",
            "SHC" : "Streethouse",
            "SRN" : "Strines",
            "STF" : "Stromeferry",
            "SOO" : "Strood",
            "STD" : "Stroud",
            "STU" : "Sturry",
            "SYA" : "Styal",
            "SUY" : "Sudbury",
            "" : "S",
            "SDH" : "Sudbury Hill Harrow",
            "SUG" : "Sugar Loaf",
            "SUM" : "Summerston",
            "SUU" : "Sunbury",
            "SUN" : "Sunderland",
            "SUP" : "Sundridge Park",
            "SNG" : "Sunningdale",
            "SNY" : "Sunnymeads",
            "SUR" : "Surbiton",
            "SUT" : "Sutton Coldfield",
            "SUC" : "Sutton Common",
            "SPK" : "Sutton Parkway",
            "" : "S",
            "SWL" : "Swale",
            "SAY" : "Swanley",
            "SWM" : "Swanscombe",
            "SWA" : "Swansea",
            "SNW" : "Swanwick",
            "SWY" : "Sway",
            "SWG" : "Swaythling",
            "SWD" : "Swinderby",
            "SWI" : "Swindon",
            "SWE" : "Swineshead",
            "" : "S",
            "" : "S",
            "SYD" : "Sydenham",
            "SYH" : "Sydenham Hill",
            "SYL" : "Syon Lane",
            "SYS" : "Syston",
            "TAC" : "Tackley",
            "TAD" : "Tadworth",
            "TAF" : "Taffs Well",
            "TAI" : "Tain",
            "TAL" : "Talsarnau",
            "TLB" : "Talybont",
            "" : "T",
            "TAB" : "Tame Bridge Parkway",
            "TAM" : "Tamworth",
            "TAP" : "Taplow",
            "TAT" : "Tattenham Corner",
            "TAU" : "Taunton",
            "TAY" : "Taynuilt",
            "TED" : "Teddington",
            "" : "T",
            "TGM" : "Teignmouth",
            "TFC" : "Telford Central",
            "TMC" : "Templecombe",
            "TEN" : "Tenby",
            "TEY" : "Teynham",
            "THD" : "Thames Ditton",
            "THA" : "Thatcham",
            "THH" : "Thatto Heath",
            "THW" : "The Hawthorns",
            "TLK" : "The Lakes",
            "THE" : "Theale",
            "TEO" : "Theobalds Grove",
            "TTF" : "Thetford",
            "THI" : "Thirsk",
            "TBY" : "Thornaby",
            "TNN" : "Thorne North",
            "TNS" : "Thorne South",
            "THO" : "Thornford",
            "THB" : "Thornliebank",
            "TNA" : "Thornton Abbey",
            "TTH" : "Thornton Heath",
            "THT" : "Thorntonhall",
            "TPB" : "Thorpe Bay",
            "TPC" : "Thorpe Culvert",
            "" : "T",
            "TBD" : "Three Bridges",
            "TOK" : "Three Oaks",
            "THU" : "Thurgarton",
            "THC" : "Thurnscoe",
            "THS" : "Thurso",
            "TRS" : "Thurston",
            "TIL" : "Tilbury Town",
            "THL" : "Tile Hill",
            "TLH" : "Tilehurst",
            "TIP" : "Tipton",
            "" : "T",
            "TIS" : "Tisbury",
            "TVP" : "Tiverton Parkway",
            "TOD" : "Todmorden",
            "TOL" : "Tolworth",
            "TPN" : "Ton Pentre",
            "TON" : "Tonbridge",
            "TDU" : "Tondu",
            "TNF" : "Tonfanau",
            "TNP" : "Tonypandy",
            "TOO" : "Tooting",
            "TOP" : "Topsham",
            "TQY" : "Torquay",
            "TRR" : "Torre",
            "TOT" : "Totnes",
            "TOM" : "Tottenham Hale",
            "TTN" : "Totton",
            "TWN" : "Town Green",
            "TRA" : "Trafford Park",
            "TRF" : "Trefforest",
            "TRE" : "Trefforest Estate",
            "TRH" : "Trehafod",
            "TRB" : "Treherbert",
            "TRY" : "Treorchy",
            "TRM" : "Trimley",
            "TRI" : "Tring",
            "" : "T",
            "TRN" : "Troon",
            "TRO" : "Trowbridge",
            "TRU" : "Truro",
            "TUL" : "Tulloch",
            "TUH" : "Tulse Hill",
            "TBW" : "Tunbridge Wells",
            "TUR" : "Turkey Street",
            "" : "T",
            "TWI" : "Twickenham",
            "TWY" : "Twyford",
            "TYC" : "Ty Croes",
            "TGS" : "Ty Glas",
            "TYG" : "Tygwyn",
            "TYL" : "Tyndrum Lower",
            "TYS" : "Tyseley",
            "TYW" : "Tywyn",
            "UCK" : "Uckfield",
            "UDD" : "Uddingston",
            "ULC" : "Ulceby",
            "ULL" : "Ulleskelf",
            "ULV" : "Ulverston",
            "UMB" : "Umberleigh",
            "UNI" : "University",
            "UHA" : "Uphall",
            "UPL" : "Upholland",
            "UPM" : "Upminster",
            "UPH" : "Upper Halliford",
            "UHL" : "Upper Holloway",
            "UTY" : "Upper Tyndrum",
            "UWL" : "Upper Warlingham",
            "UPT" : "Upton",
            "UPW" : "Upwey",
            "URM" : "Urmston",
            "UTT" : "Uttoxeter",
            "VAL" : "Valley",
            "VXH" : "Vauxhall",
            "VIR" : "Virginia Water",
            "WDO" : "Waddon",
            "WAD" : "Wadhurst",
            "WFL" : "Wainfleet",
            "WKK" : "Wakefield Kirkgate",
            "WKF" : "Wakefield Westgate",
            "WKD" : "Walkden",
            "WLG" : "Wallasey Grove Road",
            "WLV" : "Wallasey Village",
            "WLT" : "Wallington",
            "WAF" : "Wallyford",
            "WAM" : "Walmer",
            "WSL" : "Walsall",
            "WDN" : "Walsden",
            "WLC" : "Waltham Cross",
            "WHC" : "Walthamstow Central",
            "" : "W",
            "" : "W",
            "WON" : "Walton on the Naze",
            "" : "W",
            "WAN" : "Wanborough",
            "WSW" : "Wandsworth Common",
            "WWR" : "Wandsworth Road",
            "WNT" : "Wandsworth Town",
            "WNP" : "Wanstead Park",
            "WBL" : "Warblington",
            "WAR" : "Ware",
            "WRM" : "Wareham",
            "WGV" : "Wargrave",
            "WMN" : "Warminster",
            "WNH" : "Warnham",
            "WBQ" : "Warrington Bank Quay",
            "WAC" : "Warrington Central",
            "WRW" : "Warwick",
            "WRP" : "Warwick Parkway",
            "WTO" : "Water Orton",
            "WBC" : "Waterbeach",
            "WTR" : "Wateringbury",
            "" : "W",
            "WFH" : "Watford High Street",
            "WFJ" : "Watford Junction",
            "WFN" : "Watford North",
            "WTG" : "Watlington",
            "" : "W",
            "" : "W",
            "WAV" : "Wavertree Tech Park",
            "WED" : "Wedgwood",
            "WEE" : "Weeley",
            "WET" : "Weeton",
            "WMG" : "Welham Green",
            "WLI" : "Welling",
            "WEL" : "Wellingborough",
            "" : "W",
            "WLP" : "Welshpool",
            "WGC" : "Welwyn Garden City",
            "WLW" : "Welwyn North",
            "WEM" : "Wem",
            "WMB" : "Wembley Central",
            "WCX" : "Wembley Stadium",
            "WMS" : "Wemyss Bay",
            "WND" : "Wendover",
            "WNN" : "Wennington",
            "WSA" : "West Allerton",
            "WBP" : "West Brompton",
            "WBY" : "West Byfleet",
            "WCL" : "West Calder",
            "WCY" : "West Croydon",
            "WDT" : "West Drayton",
            "WDU" : "West Dulwich",
            "WEA" : "West Ealing",
            "WEH" : "West Ham",
            "WHD" : "West Hampstead",
            "WHP" : "West Hampstead Thameslink",
            "WHR" : "West Horndon",
            "WKB" : "West Kilbride",
            "WKI" : "West Kirby",
            "WMA" : "West Malling",
            "WNW" : "West Norwood",
            "WRU" : "West Ruislip",
            "WRN" : "West Runton",
            "WLD" : "West St Leonards",
            "WSU" : "West Sutton",
            "WWI" : "West Wickham",
            "WWO" : "West Worthing",
            "" : "W",
            "WCF" : "Westcliff",
            "WCB" : "Westcombe Park",
            "WHA" : "Westenhanger",
            "WTA" : "Wester Hailes",
            "WFI" : "Westerfield",
            "WES" : "Westerton",
            "" : "W",
            "WHG" : "Westhoughton",
            "WNM" : "Weston Milton",
            "" : "W",
            "WRL" : "Wetheral",
            "WYB" : "Weybridge",
            "WEY" : "Weymouth",
            "WBR" : "Whaley Bridge",
            "WHE" : "Whalley",
            "WTS" : "Whatstandwell",
            "WFF" : "Whifflet",
            "WHM" : "Whimple",
            "WNL" : "Whinhill",
            "WHN" : "Whiston",
            "WTB" : "Whitby",
            "" : "W",
            "" : "W",
            "" : "W",
            "WHL" : "White Hart Lane",
            "WNY" : "White Notley",
            "WCR" : "Whitecraigs",
            "WTH" : "Whitehaven",
            "WTL" : "Whitland",
            "WBD" : "Whitley Bridge",
            "WTE" : "Whitlocks End",
            "WHI" : "Whitstable",
            "WLE" : "Whittlesea",
            "WLF" : "Whittlesford Parkway",
            "WTN" : "Whitton",
            "WWL" : "Whitwell",
            "WHY" : "Whyteleafe",
            "WHS" : "Whyteleafe South",
            "WCK" : "Wick",
            "WIC" : "Wickford",
            "WCM" : "Wickham Market",
            "WDD" : "Widdrington",
            "WID" : "Widnes",
            "WMR" : "Widney Manor",
            "WGN" : "Wigan North Western",
            "WGW" : "Wigan Wallgate",
            "WGT" : "Wigton",
            "WMI" : "Wildmill",
            "WIJ" : "Willesden Junction",
            "WLM" : "Williamwood",
            "WIL" : "Willington",
            "WMC" : "Wilmcote",
            "WML" : "Wilmslow",
            "WNE" : "Wilnecote",
            "WIM" : "Wimbledon",
            "WBO" : "Wimbledon Chase",
            "WSE" : "Winchelsea",
            "WIN" : "Winchester",
            "WNF" : "Winchfield",
            "WIH" : "Winchmore Hill",
            "WDM" : "Windermere",
            "" : "W",
            "" : "W",
            "WNS" : "Winnersh",
            "WTI" : "Winnersh Triangle",
            "WSF" : "Winsford",
            "WSH" : "Wishaw",
            "WTM" : "Witham",
            "WTY" : "Witley",
            "WTT" : "Witton",
            "WVF" : "Wivelsfield",
            "WIV" : "Wivenhoe",
            "WOB" : "Woburn Sands",
            "WOK" : "Woking",
            "WKM" : "Wokingham",
            "WOH" : "Woldingham",
            "WVH" : "Wolverhampton",
            "WOL" : "Wolverton",
            "WOM" : "Wombwell",
            "WDE" : "Wood End",
            "WST" : "Wood Street",
            "WDB" : "Woodbridge",
            "WGR" : "Woodgrange Park",
            "WDL" : "Woodhall",
            "WDH" : "Woodhouse",
            "WDS" : "Woodlesford",
            "WLY" : "Woodley",
            "WME" : "Woodmansterne",
            "WSR" : "Woodsmoor",
            "WOO" : "Wool",
            "WLS" : "Woolston",
            "WWA" : "Woolwich Arsenal",
            "WWD" : "Woolwich Dockyard",
            "WWW" : "Wooten Wawen",
            "WOF" : "Worcester Foregate Street",
            "WCP" : "Worcester Park",
            "WOS" : "Worcester Shrub Hill",
            "WKG" : "Workington",
            "WRK" : "Worksop",
            "WOR" : "Worle",
            "WPL" : "Worplesdon",
            "WRT" : "Worstead",
            "WRH" : "Worthing",
            "WRB" : "Wrabness",
            "WRY" : "Wraysbury",
            "WRE" : "Wrenbury",
            "WRS" : "Wressle",
            "WXC" : "Wrexham Central",
            "WRX" : "Wrexham General",
            "WYE" : "Wye",
            "WYM" : "Wylam",
            "WYL" : "Wylde Green",
            "WMD" : "Wymondham",
            "WYT" : "Wythall",
            "YAL" : "Yalding",
            "YRD" : "Yardley Wood",
            "YRM" : "Yarm",
            "YAE" : "Yate",
            "YAT" : "Yatton",
            "YEO" : "Yeoford",
            "YVJ" : "Yeovil Junction",
            "YVP" : "Yeovil Pen Mill",
            "YET" : "Yetminster",
            "YNW" : "Ynyswen",
            "YOK" : "Yoker",
            "YRK" : "York",
            "YRT" : "Yorton",
            "YSM" : "Ystrad Mynach",
            "YSR" : "Ystrad Rhondda",
            }
        
class docs (fakesubwayapis.fakesubwayapidocs, ukrail) :

    def __init__ (self) :

        fakesubwayapis.fakesubwayapidocs.__init__(self)
        ukrail.__init__(self)
        
    def get (self) :

        stations = self.prepare_stations()
        
        self.display("ukrail.html", {'title' : 'ukrail', 'stations' : stations})
        return

class api (fakesubwayapis.fakesubwayapi, ukrail) :

    def __init__ (self) :

        fakesubwayapis.fakesubwayapi.__init__(self)
        ukrail.__init__(self)
        
class getinfo (api) :

    def get (self, code) :

        code = code.upper()
        
        if not self.stations.has_key(code) :
            self.api_error(404, 'Station not found')
            return

        out = {
            'code' : code,
            'service' : 'ukrail',
            'name' :  { '_content' : self.stations[code] },
            'url' : { '_content' : 'http://www.nationalrail.co.uk/stations/%s/details.html' % code.lower() },
            }
        
        self.api_ok({'station' : out})
        return
